// Tables, equal-slice charts, and regression. These constructors expand into
// stable native children; the logical Canvas entity retains every child/tag id.

import { argName, argNumber, argPoint, argString, escapeString, num, pt } from "../args.js";
import { registerEntity, type Box, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import type { LeastSquaresEntity, PieEntity, Point, TableEntity, VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

export interface TableGrid { rows:string[][];columnLabels:string[];rowLabels:string[];issue:string|null; }
export interface TableLayout { x0:number;y0:number;width:number;height:number;columnWidth:number;rowHeight:number;gridRows:number;gridColumns:number;hasColumnLabels:boolean;hasRowLabels:boolean;cell:(row:number,column:number)=>Point; }
export interface RegressionGeometry { points:Point[];residuals:{from:Point;to:Point}[];line:{from:Point;to:Point};label:Point;slope:number;intercept:number;equation:string; }

const move=(e:{x:number;y:number},dx:number,dy:number)=>{e.x+=dx;e.y+=dy;};
const tokens=(source:string)=>source.split(/[\s,]+/u).filter(Boolean);
const effectiveTableWidth=(e:TableEntity)=>e.columnWidth??120,effectiveTableHeight=(e:TableEntity)=>e.rowHeight??64;

export function tableGrid(entity:Pick<TableEntity,"source"|"columnLabels"|"rowLabels">):TableGrid{
  const rows=entity.source.split(";").map(tokens).filter(row=>row.length),columnLabels=entity.columnLabels===null?[]:tokens(entity.columnLabels),rowLabels=entity.rowLabels===null?[]:tokens(entity.rowLabels);
  if(!rows.length)return{rows,columnLabels,rowLabels,issue:"Table has no entries."};const count=rows[0].length;
  return{rows,columnLabels,rowLabels,issue:rows.some(row=>row.length!==count)?"Every table row must contain the same number of cells.":null};
}
export function tableLayout(entity:TableEntity):TableLayout{
  const grid=tableGrid(entity),columns=grid.rows[0]?.length??1,hasColumnLabels=grid.columnLabels.length>0,hasRowLabels=grid.rowLabels.length>0,gridRows=grid.rows.length+(hasColumnLabels?1:0),gridColumns=columns+(hasRowLabels?1:0),columnWidth=effectiveTableWidth(entity),rowHeight=effectiveTableHeight(entity),width=gridColumns*columnWidth,height=gridRows*rowHeight,x0=entity.x-width/2,y0=entity.y-height/2;
  return{x0,y0,width,height,columnWidth,rowHeight,gridRows,gridColumns,hasColumnLabels,hasRowLabels,cell:(row,column)=>({x:x0+(column+.5)*columnWidth,y:y0+(row+.5)*rowHeight})};
}
export function tableReferences(entity:TableEntity):string[]{const grid=tableGrid(entity);if(grid.issue)return[];const layout=tableLayout(entity),rows=grid.rows.length,cols=grid.rows[0].length;return[`${entity.id}.entries`,`${entity.id}.labels`,`${entity.id}.hlines`,`${entity.id}.vlines`,`${entity.id}.lines`,...Array.from({length:rows},(_v,i)=>`${entity.id}.row${i}`),...Array.from({length:cols},(_v,i)=>`${entity.id}.col${i}`),...Array.from({length:rows},(_v,i)=>`${entity.id}.rowlabel${i}`),...Array.from({length:cols},(_v,i)=>`${entity.id}.collabel${i}`),...grid.rows.flatMap((row,i)=>row.map((_v,j)=>`${entity.id}.r${i}c${j}`)),...Array.from({length:layout.gridRows+1},(_v,i)=>`${entity.id}.h${i}`),...Array.from({length:layout.gridColumns+1},(_v,i)=>`${entity.id}.v${i}`)];}

export function leastSquaresGeometry(entity:LeastSquaresEntity):{geometry:RegressionGeometry|null;issue:string|null}{
  const values=tokens(entity.source).flatMap(token=>{const value=Number(token);return Number.isFinite(value)?[value]:[];});if(values.length<4||values.length%2)return{geometry:null,issue:"Least squares needs an even list of at least two points."};
  const raw=Array.from({length:values.length/2},(_v,i)=>({x:values[i*2],y:values[i*2+1]})),n=raw.length,sx=raw.reduce((a,p)=>a+p.x,0),sy=raw.reduce((a,p)=>a+p.y,0),sxx=raw.reduce((a,p)=>a+p.x*p.x,0),sxy=raw.reduce((a,p)=>a+p.x*p.y,0),den=n*sxx-sx*sx;if(Math.abs(den)<1e-9)return{geometry:null,issue:"All points share one x; no y = mx + c fit exists."};
  const slope=(n*sxy-sx*sy)/den,intercept=(sy-slope*sx)/n,minX=Math.min(...raw.map(p=>p.x)),maxX=Math.max(...raw.map(p=>p.x)),pad=(maxX-minX)*.12+.5,screen=(p:Point):Point=>({x:entity.x+p.x*entity.unit,y:entity.y-p.y*entity.unit}),fromRaw={x:minX-pad,y:slope*(minX-pad)+intercept},toRaw={x:maxX+pad,y:slope*(maxX+pad)+intercept},mid=(fromRaw.x+toRaw.x)/2,sign=intercept>=0?"+":"-";
  return{geometry:{points:raw.map(screen),residuals:raw.map(p=>({from:screen(p),to:screen({x:p.x,y:slope*p.x+intercept})})),line:{from:screen(fromRaw),to:screen(toRaw)},label:{x:screen({x:mid,y:slope*mid+intercept}).x-40,y:screen({x:mid,y:slope*mid+intercept}).y-34},slope,intercept,equation:`y = ${slope.toFixed(2)} x ${sign} ${Math.abs(intercept).toFixed(2)}`},issue:null};
}

function childStyle(entity:{childStyles:Record<string,VirtualChildStyle>},ref:string):VirtualChildStyle{return entity.childStyles[ref]??(entity.childStyles[ref]={});}
function applyChild(entity:{childStyles:Record<string,VirtualChildStyle>},ref:string,stmt:CallStatement):boolean{const style=childStyle(entity,ref);switch(stmt.name){case"color":{const value=argName(stmt.args,1);if(!value)return false;style.color=value;return true;}case"opacity":{const value=argNumber(stmt.args,1);if(value===null)return false;style.opacity=value;return true;}case"hidden":style.reveal=argName(stmt.args,1)==="center"?"grow":"fade";return true;case"untraced":style.untraced=true;return true;default:return false;}}
function childLines(styles:Record<string,VirtualChildStyle>):string[]{return Object.entries(styles).flatMap(([ref,style])=>[...(style.color?[`color(${ref}, ${style.color});`]:[]),...(style.opacity!==undefined?[`opacity(${ref}, ${num(style.opacity)});`]:[]),...(style.reveal?[`hidden(${ref}${style.reveal==="grow"?", center":""});`]:[]),...(style.untraced?[`untraced(${ref});`]:[])]);}
function story(refs:readonly string[],kind:(ref:string)=>StoryTargetSpec["kind"]):StoryTargetSpec[]{return refs.map(id=>({id,label:id,kind:kind(id)}));}
function leastReferences(entity:LeastSquaresEntity):string[]{const count=Math.floor(tokens(entity.source).filter(value=>Number.isFinite(Number(value))).length/2);return[`${entity.id}.line`,`${entity.id}.points`,`${entity.id}.residuals`,`${entity.id}.eq`,...Array.from({length:count},(_v,i)=>`${entity.id}.r${i}`),...Array.from({length:count},(_v,i)=>`${entity.id}.p${i}`)];}

registerEntity<TableEntity>({kind:"table",ctor:"table",aliases:["mathtable","integertable","decimaltable"],group:"Math",label:"Ruled data table",icon:"▦",order:43,fidelity:"exact",hint:"Editable entries and headers with addressable cells, rows, columns, labels, and rules",anchorArgIndex:2,
  create:(id,x,y)=>({...baseEntity(id,"fg"),nativePaint:true,kind:"table",spelling:"table",source:"1 2; 3 4",x,y,columnWidth:120,rowHeight:64,columnLabels:null,rowLabels:null,childStyles:{}}),parseArgs(stmt){const id=argName(stmt.args,0),source=argString(stmt.args,1),at=argPoint(stmt.args,2),cw=argNumber(stmt.args,3),rh=argNumber(stmt.args,4),cols=argString(stmt.args,5),rows=argString(stmt.args,6);if(!id||source===null||!at||stmt.args.length<3||stmt.args.length>7||(stmt.args.length>=4&&cw===null)||(stmt.args.length>=5&&rh===null)||(stmt.args.length>=6&&cols===null)||(stmt.args.length>=7&&rows===null))return null;return{...baseEntity(id,"fg"),nativePaint:true,kind:"table",spelling:stmt.name as TableEntity["spelling"],source,x:at.x,y:at.y,columnWidth:cw,rowHeight:rh,columnLabels:cols,rowLabels:rows,childStyles:{}};},ctorLine(e){let tail="";if(e.columnWidth!==null||e.rowHeight!==null||e.columnLabels!==null||e.rowLabels!==null)tail+=`, ${num(e.columnWidth??120)}`;if(e.rowHeight!==null||e.columnLabels!==null||e.rowLabels!==null)tail+=`, ${num(e.rowHeight??64)}`;if(e.columnLabels!==null||e.rowLabels!==null)tail+=`, "${escapeString(e.columnLabels??"")}"`;if(e.rowLabels!==null)tail+=`, "${escapeString(e.rowLabels)}"`;return`${e.spelling}(${e.id}, "${escapeString(e.source)}", ${pt(e.x,e.y)}${tail});`;},extraLines:e=>childLines(e.childStyles),modifiers:{},referenceIds:tableReferences,storyTargets(e){const refs=tableReferences(e);return story(refs,ref=>ref.includes(".h")||ref.includes(".v")||ref.endsWith(".lines")||ref.endsWith(".hlines")||ref.endsWith(".vlines")?"line":"text");},applyReferenceModifier(e,ref,stmt){return applyChild(e,ref,stmt);},anchor:e=>({x:e.x,y:e.y}),translate:move,bounds(e){const l=tableLayout(e);return{x:l.x0,y:l.y0,width:l.width,height:l.height};},handles:e=>{const l=tableLayout(e);return[{name:"cell",x:e.x+l.columnWidth/2,y:e.y+l.rowHeight/2}];},dragHandle(e,_h,px,py){e.columnWidth=Math.max(20,Math.abs(px-e.x)*2);e.rowHeight=Math.max(20,Math.abs(py-e.y)*2);},fields:[{key:"source",label:"Body cells",input:"textarea",hint:"Rows use semicolons; cells split on whitespace or commas."},{key:"columnLabels",label:"Column labels",input:"text",nullable:true},{key:"rowLabels",label:"Row labels",input:"text",nullable:true},{key:"columnWidth",label:"Cell width",input:"number",nullable:true,min:20,step:4},{key:"rowHeight",label:"Cell height",input:"number",nullable:true,min:20,step:4}]});

registerEntity<PieEntity>({kind:"pie",ctor:"pie",group:"Math",label:"Equal-slice pie",icon:"◔",order:43.1,fidelity:"exact",hint:"Filled equal sectors; every slice is independently Story-addressable",anchorArgIndex:1,
  create:(id,x,y)=>({...baseEntity(id,"panel"),nativePaint:true,kind:"pie",x,y,radius:140,slices:6,paint:"default",strokeWidth:null,outlineColor:null,childStyles:{}}),parseArgs(stmt){const id=argName(stmt.args,0),at=argPoint(stmt.args,1),radius=argNumber(stmt.args,2),slices=argNumber(stmt.args,3);return id&&at&&radius!==null&&slices!==null&&stmt.args.length===4?{...baseEntity(id,"panel"),nativePaint:true,kind:"pie",x:at.x,y:at.y,radius,slices:Math.trunc(slices),paint:"default",strokeWidth:null,outlineColor:null,childStyles:{}}:null;},ctorLine:e=>`pie(${e.id}, ${pt(e.x,e.y)}, ${num(e.radius)}, ${num(Math.trunc(e.slices))});`,extraLines:e=>[...(e.paint==="default"?[]:[`${e.paint}(${e.id});`]),...(e.strokeWidth===null?[]:[`stroke(${e.id}, ${num(e.strokeWidth)});`]),...(e.outlineColor===null?[]:[`outline(${e.id}, ${e.outlineColor});`]),...childLines(e.childStyles)],modifiers:{outlined(e){e.paint="outlined";return true;},filled(e){e.paint="filled";return true;},stroke(e,stmt){const value=argNumber(stmt.args,1);if(value===null)return false;e.strokeWidth=value;return true;},outline(e,stmt){const value=argName(stmt.args,1);if(!value)return false;e.outlineColor=value;return true;}},referenceIds:e=>Array.from({length:Math.max(0,Math.min(360,Math.trunc(e.slices)))},(_v,i)=>`${e.id}${i}`),storyTargets(e){return story(Array.from({length:Math.max(0,Math.min(360,Math.trunc(e.slices)))},(_v,i)=>`${e.id}${i}`),()=>"sector");},applyReferenceModifier(e,ref,stmt){return applyChild(e,ref,stmt);},anchor:e=>({x:e.x,y:e.y}),translate:move,bounds:e=>({x:e.x-e.radius,y:e.y-e.radius,width:e.radius*2,height:e.radius*2}),handles:e=>[{name:"radius",x:e.x+e.radius,y:e.y}],dragHandle(e,_h,px,py){e.radius=Math.max(1,Math.hypot(px-e.x,py-e.y));},fields:[{key:"radius",label:"Radius",input:"number",min:1,step:1},{key:"slices",label:"Equal slices",input:"number",min:1,max:360,step:1}]});

registerEntity<LeastSquaresEntity>({kind:"leastsquares",ctor:"leastsquares",group:"Math",label:"Least-squares fit",icon:"•╱•",order:43.2,fidelity:"exact",hint:"Best-fit line, data points, vertical residuals, and equation",anchorArgIndex:1,
  create:(id,x,y)=>({...baseEntity(id,"cyan"),nativePaint:true,kind:"leastsquares",x,y,unit:40,source:"1 2 2 3 3 5 4 4 5 6",constructorColor:null,childStyles:{}}),parseArgs(stmt){const id=argName(stmt.args,0),at=argPoint(stmt.args,1),unit=argNumber(stmt.args,2),source=argString(stmt.args,3),color=argName(stmt.args,4);return id&&at&&unit!==null&&source!==null&&stmt.args.length>=4&&stmt.args.length<=5&&(stmt.args.length===4||color)?{...baseEntity(id,color??"cyan"),nativePaint:true,kind:"leastsquares",x:at.x,y:at.y,unit,source,constructorColor:color,childStyles:{}}:null;},ctorLine:e=>`leastsquares(${e.id}, ${pt(e.x,e.y)}, ${num(e.unit)}, "${escapeString(e.source)}"${e.constructorColor?`, ${e.constructorColor}`:""});`,extraLines:e=>childLines(e.childStyles),modifiers:{},referenceIds:leastReferences,storyTargets(e){return story(leastReferences(e),ref=>ref.endsWith(".eq")?"text":ref.includes(".p")||ref.endsWith(".points")?"dot":"line");},applyReferenceModifier(e,ref,stmt){return applyChild(e,ref,stmt);},anchor:e=>({x:e.x,y:e.y}),translate:move,bounds(e){const result=leastSquaresGeometry(e);if(!result.geometry)return{x:e.x-150,y:e.y-60,width:300,height:120};const pts=[...result.geometry.points,result.geometry.line.from,result.geometry.line.to,result.geometry.label],xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);return{x:Math.min(...xs)-24,y:Math.min(...ys)-24,width:Math.max(...xs)-Math.min(...xs)+48,height:Math.max(...ys)-Math.min(...ys)+48};},handles:()=>[],dragHandle(){},fields:[{key:"source",label:"Point pairs",input:"textarea",hint:"x1 y1 x2 y2 …; at least two points with more than one x."},{key:"unit",label:"Pixels per unit",input:"number",min:.1,step:1}]});
