// ML kit declarations. Canvas shows editable structure and dependencies;
// numerical execution and training state remain native Preview authority.

import { argName, argNumber, argPoint, argString, escapeString, num, pt } from "../args.js";
import { preferReference, registerEntity, type Box, type FieldSpec, type GeometryContext, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import type { MlEntity, MlKind, Point, SceneDoc, VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

export const ML_CANVAS_UNIT_CAP = 9;

export interface MlTensorGrid { channels: number; rows: number; cols: number; values: number[][][]; cells: Array<{ id: string; value: number; channel: number; row: number; col: number; x: number; y: number; size: number }>; issue: string | null }

const move = (entity: MlEntity, dx: number, dy: number) => { entity.x += dx; entity.y += dy; };
const words = (source: string) => source.trim().split(/[\s,]+/u).filter(Boolean);
const numberWords = (source: string) => words(source).flatMap((word) => { const value = Number(word); return Number.isFinite(value) ? [value] : []; });

function digitArt(value: string): string {
  const glyphs: Record<string, string[]> = {
    "0": [".###.", "#...#", "#...#", "#...#", ".###."], "1": ["..#..", ".##..", "..#..", "..#..", ".###."],
    "2": [".###.", "....#", ".###.", "#....", "#####"], "3": ["####.", "....#", ".###.", "....#", "####."],
    "4": ["#..#.", "#..#.", "#####", "...#.", "...#."], "5": ["#####", "#....", "####.", "....#", "####."],
    "6": [".###.", "#....", "####.", "#...#", ".###."], "7": ["#####", "...#.", "..#..", ".#...", ".#..."],
    "8": [".###.", "#...#", ".###.", "#...#", ".###."], "9": [".###.", "#...#", ".####", "....#", ".###."],
  };
  return (glyphs[value.trim()] ?? glyphs["5"]).map((row) => row.replaceAll(".", "0 ").replaceAll("#", "1 ").trim()).join(";");
}

export function mlTensorGrid(entity: MlEntity): MlTensorGrid {
  const source = entity.kind === "digit" ? digitArt(entity.source) : entity.source;
  const rawChannels = source.split("|").map((channel) => channel.trim()).filter(Boolean), parsed = rawChannels.map((channel) => channel.split(";").map(numberWords).filter((row) => row.length));
  const channels = parsed.length, rows = parsed[0]?.length ?? 0, cols = parsed[0]?.[0]?.length ?? 0;
  if (!channels || !rows || !cols || parsed.some((channel) => channel.length !== rows || channel.some((row) => row.length !== cols))) return { channels, rows, cols, values: parsed, cells: [], issue: "Tensor channels must be equally sized numeric rows." };
  const cell = entity.p1 ?? (entity.kind === "digit" ? 18 : 48), spread = (channels - 1) * cell * .34;
  const cells = parsed.flatMap((channel, channelIndex) => channel.flatMap((row, rowIndex) => row.map((value, colIndex) => ({ id: `${entity.id}.c${channelIndex}.r${rowIndex}c${colIndex}`, value, channel: channelIndex, row: rowIndex, col: colIndex, x: entity.x + channelIndex * cell * .34 - spread / 2 + (colIndex - (cols - 1) / 2) * cell, y: entity.y - channelIndex * cell * .34 + spread / 2 + (rowIndex - (rows - 1) / 2) * cell, size: cell }))));
  return { channels, rows, cols, values: parsed, cells, issue: null };
}

export function mlTokens(entity: MlEntity): string[] {
  if (entity.kind === "attention") return entity.source.split("|").map((token) => token.trim()).filter(Boolean);
  if (entity.mode === "authored") return entity.source.split("|").map((token) => token.trim()).filter(Boolean);
  if (entity.mode === "character" || entity.mode === "char") return [...entity.source];
  return entity.source.match(/[\p{L}\p{N}_]+|[^\s\p{L}\p{N}_]/gu) ?? [];
}

export function mlLayers(entity: MlEntity): number[] { return words(entity.source).map(Number).filter((value) => Number.isFinite(value) && value > 0).map(Math.trunc); }

export function mlOutputShape(entity: MlEntity, doc?: SceneDoc): { channels: number; rows: number; cols: number; steps: number; issue: string | null } {
  const source = doc?.entities.find((candidate) => candidate.id === entity.ref && ["tensor", "digit", "convolve", "pool"].includes(candidate.kind)) as MlEntity | undefined;
  if (!source) return { channels: 0, rows: 0, cols: 0, steps: 0, issue: `Missing tensor input “${entity.ref}”.` };
  const input = source.kind === "tensor" || source.kind === "digit" || source.kind === "kernel" ? mlTensorGrid(source) : mlOutputShape(source, doc);
  if (input.issue) return { channels: 0, rows: 0, cols: 0, steps: 0, issue: input.issue };
  const window = entity.kind === "pool" ? Math.max(1, Math.trunc(entity.p1 ?? 2)) : (() => { const kernel = doc?.entities.find((candidate) => candidate.id === entity.ref2 && candidate.kind === "kernel") as MlEntity | undefined; return kernel ? mlTensorGrid(kernel).rows : 0; })();
  if (!window) return { channels: 0, rows: 0, cols: 0, steps: 0, issue: `Missing kernel “${entity.ref2}”.` };
  const stride = Math.max(1, Math.trunc(entity.kind === "pool" ? entity.p2 ?? window : entity.p1 ?? 1)), padding = Math.max(0, Math.trunc(entity.kind === "pool" ? entity.p3 ?? 0 : entity.p2 ?? 0));
  const rows = Math.floor((input.rows + padding * 2 - window) / stride) + 1, cols = Math.floor((input.cols + padding * 2 - window) / stride) + 1, channels = input.channels;
  return rows > 0 && cols > 0 ? { channels, rows, cols, steps: channels * rows * cols, issue: null } : { channels, rows, cols, steps: 0, issue: "Window is larger than the padded tensor." };
}

function childStyle(entity: MlEntity, ref: string): VirtualChildStyle { return entity.childStyles[ref] ?? (entity.childStyles[ref] = {}); }
function applyChild(entity: MlEntity, ref: string, stmt: CallStatement): boolean { const style = childStyle(entity, ref); if (stmt.name === "color") { const value = argName(stmt.args, 1); if (!value) return false; style.color = value; return true; } if (stmt.name === "opacity") { const value = argNumber(stmt.args, 1); if (value === null) return false; style.opacity = value; return true; } if (stmt.name === "hidden") { style.reveal = argName(stmt.args, 1) === "center" ? "grow" : "fade"; return true; } if (stmt.name === "untraced") { style.untraced = true; return true; } return false; }
function childLines(styles: Record<string, VirtualChildStyle>): string[] { return Object.entries(styles).flatMap(([ref, style]) => [...(style.color ? [`color(${ref}, ${style.color});`] : []), ...(style.opacity !== undefined ? [`opacity(${ref}, ${num(style.opacity)});`] : []), ...(style.reveal ? [`hidden(${ref}${style.reveal === "grow" ? ", center" : ""});`] : []), ...(style.untraced ? [`untraced(${ref});`] : [])]); }
function base(id: string, kind: MlKind, x: number, y: number): MlEntity { return { ...baseEntity(id, "cyan"), nativePaint: true, kind, x, y, source: "", source2: "", ref: "", ref2: "", mode: "", p1: null, p2: null, p3: null, p4: null, p5: null, constructorColor: null, childStyles: {} }; }
function optNums(stmt: CallStatement, from: number, count: number): Array<number | null> | null { const values = Array.from({ length: count }, (_unused, index) => argNumber(stmt.args, from + index)); for (let i = 0; i < count; i++) if (stmt.args.length > from + i && values[i] === null) return null; return values; }
function optionalTail(values: Array<number | null>, defaults: number[]): string { let last = values.length - 1; while (last >= 0 && values[last] === null) last--; return Array.from({ length: last + 1 }, (_unused, index) => `, ${num(values[index] ?? defaults[index])}`).join(""); }

function mlRefs(entity: MlEntity): string[] {
  if (["tensor", "digit", "kernel"].includes(entity.kind)) { const grid = mlTensorGrid(entity); return [`${entity.id}.cells`, `${entity.id}.values`, `${entity.id}.labels`, `${entity.id}.label`, ...Array.from({ length: grid.channels }, (_unused, i) => `${entity.id}.channel${i}`), ...Array.from({ length: grid.rows }, (_unused, i) => `${entity.id}.row${i}`), ...Array.from({ length: grid.cols }, (_unused, i) => `${entity.id}.col${i}`), ...grid.cells.flatMap((cell) => [cell.id, `${cell.id}.value`])]; }
  if (entity.kind === "network") { const layers = mlLayers(entity); return [`${entity.id}.nodes`, `${entity.id}.edges`, `${entity.id}.input`, `${entity.id}.hidden`, `${entity.id}.output`, `${entity.id}.status`, `${entity.id}.gradients`, ...layers.flatMap((count, layer) => [`${entity.id}.layer${layer}`, `${entity.id}.layer${layer}.label`, ...Array.from({ length: Math.min(count, ML_CANVAS_UNIT_CAP) }, (_unused, unit) => `${entity.id}.l${layer}.n${unit}`)])]; }
  if (entity.kind === "tokenize") return [`${entity.id}.tokens`, `${entity.id}.labels`, `${entity.id}.indices`, `${entity.id}.heading`, `${entity.id}.source`, ...mlTokens(entity).flatMap((_token, i) => [`${entity.id}.token${i}`, `${entity.id}.token${i}.box`, `${entity.id}.token${i}.text`, `${entity.id}.token${i}.index`])];
  if (entity.kind === "activation") return [`${entity.id}.axes`, `${entity.id}.xaxis`, `${entity.id}.yaxis`, `${entity.id}.curve`, `${entity.id}.label`];
  const groups: Record<string, string[]> = {
    convolve: ["cells", "values", "label", "scan.source", "scan.operator", "scan.output", "scan.pick", "scan.status"], pool: ["cells", "values", "label", "scan.source", "scan.output", "scan.pick", "scan.status"],
    embedding: ["heading", "tokens", "rows", "values", "positions", "combined", "status"], transformer: ["heading", "input", "heads", "attention", "concat", "residual1", "norm1", "mlp", "residual2", "norm2", "output", "status"],
    logits: ["panel", "heading", "source", "temperature", "candidates", "status"], attention: ["heading", "tokens", "queries", "keys", "values", "matrix", "output", "residuals", "status"], topk: ["title", "ranks", "status"],
  };
  return (groups[entity.kind] ?? []).map((suffix) => `${entity.id}.${suffix}`);
}
function bounds(entity: MlEntity, ctx?: GeometryContext): Box {
  if (["tensor", "digit", "kernel"].includes(entity.kind)) { const grid = mlTensorGrid(entity), cell = entity.p1 ?? (entity.kind === "digit" ? 18 : 48), width = Math.max(1, grid.cols) * cell + Math.max(0, grid.channels - 1) * cell * .34, height = Math.max(1, grid.rows) * cell + Math.max(0, grid.channels - 1) * cell * .34 + 46; return { x: entity.x - width / 2, y: entity.y - height / 2 - 18, width, height }; }
  if (entity.kind === "activation") return { x: entity.x - (entity.p1 ?? 360) / 2, y: entity.y - (entity.p2 ?? 220) / 2, width: entity.p1 ?? 360, height: entity.p2 ?? 220 };
  if (entity.kind === "tokenize") return { x: entity.x - (entity.p1 ?? 760) / 2, y: entity.y - 95, width: entity.p1 ?? 760, height: 160 };
  const width = entity.kind === "network" ? entity.p1 ?? 700 : entity.kind === "embedding" ? entity.p1 ?? 1040 : entity.kind === "transformer" ? entity.p1 ?? 1120 : entity.kind === "attention" ? entity.p1 ?? 900 : entity.kind === "topk" ? entity.p2 ?? 420 : entity.kind === "logits" ? entity.p2 ?? 760 : Math.max(300, (ctx?.bounds(entity.ref)?.width ?? 300) * .7);
  const height = entity.kind === "network" ? entity.p2 ?? 420 : entity.kind === "embedding" ? entity.p2 ?? 460 : entity.kind === "transformer" ? entity.p2 ?? 520 : entity.kind === "attention" ? entity.p2 ?? 430 : entity.kind === "topk" ? entity.p3 ?? 230 : entity.kind === "logits" ? entity.p3 ?? 440 : Math.max(180, (ctx?.bounds(entity.ref)?.height ?? 220) * .7);
  return { x: entity.x - width / 2, y: entity.y - height / 2, width, height };
}
function common(kind: MlKind, ctor: string, label: string, icon: string, order: number, fidelity: "exact" | "semantic", fields: FieldSpec[], create: (entity: MlEntity, doc?: SceneDoc, selected?: string) => void, parse: (stmt: CallStatement, entity: MlEntity) => boolean, serialize: (entity: MlEntity) => string, dependencyKinds: MlKind[] = []) {
  registerEntity<MlEntity>({ kind, ctor, group: "ML", label, icon, order, fidelity, hint: fidelity === "exact" ? "Editable native ML figure with stable generated children" : "Editable ML contract and dependencies; Preview owns numerical execution", anchorArgIndex: kind === "convolve" ? 3 : kind === "pool" ? 2 : kind === "embedding" || kind === "transformer" ? 2 : kind === "logits" || kind === "topk" ? 3 : 1,
    create(id, x, y, doc, selected) { const entity = base(id, kind, x, y); create(entity, doc, selected); return entity; }, canCreate: dependencyKinds.length ? (doc) => doc.entities.some((entity) => dependencyKinds.includes(entity.kind as MlKind)) : undefined, createBlockedReason: dependencyKinds.length ? `Add ${dependencyKinds.join(" or ")} first.` : undefined,
    parseArgs(stmt) { const id = argName(stmt.args, 0); if (!id) return null; const pointIndex = kind === "convolve" || kind === "logits" || kind === "topk" ? 3 : kind === "pool" || kind === "embedding" || kind === "transformer" ? 2 : 1, at = argPoint(stmt.args, pointIndex); if (!at) return null; const entity = base(id, kind, at.x, at.y); return parse(stmt, entity) ? entity : null; }, ctorLine: serialize, extraLines: (entity) => childLines(entity.childStyles), modifiers: {}, references: (entity) => [entity.ref, entity.ref2].filter(Boolean), replaceReference(entity, from, to) { if (entity.ref === from) entity.ref = to; if (entity.ref2 === from) entity.ref2 = to; }, referenceIds: mlRefs, storyTargets(entity) { return mlRefs(entity).map((id): StoryTargetSpec => ({ id, label: id, kind: id.includes("cell") || id.includes("box") || id.includes("panel") ? "rect" : id.includes("node") ? "dot" : id.includes("label") || id.includes("status") || id.includes("heading") ? "text" : "line" })); }, applyReferenceModifier: applyChild, anchor: (entity) => ({ x: entity.x, y: entity.y }), translate: move, bounds, handles: () => [], dragHandle() {}, fields });
}

const textField = (key: string, label: string, hint?: string): FieldSpec => ({ key, label, input: "textarea", hint });
const numField = (key: string, label: string, nullable = true, min?: number, step = 1): FieldSpec => ({ key, label, input: "number", nullable, min, step });
const refField = (key: string, label: string, kinds: MlKind[]): FieldSpec => ({ key, label, input: "entity", entityKinds: kinds, referencesEarlierOnly: true });

common("network", "network", "Neural network", "◉⇢◉", 80, "semantic", [textField("source", "Layer sizes", "Example: 3 6 4 3"), textField("source2", "Activations", "One per transition: relu tanh softmax"), numField("p1", "Width", true, 240), numField("p2", "Height", true, 180), numField("p3", "Seed", true, 0)], (e) => { e.source = "3 6 4 3"; e.source2 = "relu tanh softmax"; }, (s, e) => { const at = argPoint(s.args, 1), a = argString(s.args, 2), b = argString(s.args, 3), ns = optNums(s, 4, 3); if (!at || a === null || b === null || !ns || s.args.length < 4 || s.args.length > 7) return false; [e.p1, e.p2, e.p3] = ns; e.source = a; e.source2 = b; return true; }, (e) => `network(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.source)}", "${escapeString(e.source2)}"${optionalTail([e.p1, e.p2, e.p3], [700, 420, 7])});`);
common("activation", "activation", "Activation function", "ƒ", 80.1, "exact", [{ key: "mode", label: "Function", input: "select", options: ["linear", "relu", "sigmoid", "tanh", "softmax"] }, numField("p1", "Width", true, 120), numField("p2", "Height", true, 100)], (e) => { e.mode = "relu"; }, (s, e) => { const mode = argName(s.args, 2), ns = optNums(s, 3, 2); if (!mode || !ns || s.args.length < 3 || s.args.length > 5) return false; e.mode = mode; [e.p1, e.p2] = ns; return true; }, (e) => `activation(${e.id}, ${pt(e.x, e.y)}, ${e.mode}${optionalTail([e.p1, e.p2], [360, 220])});`);
for (const [kind, label, fallback, paint] of [["tensor", "Tensor", 48, "cyan"], ["digit", "Digit tensor", 18, "cyan"], ["kernel", "Kernel", 48, "magenta"]] as const) common(kind, kind, label, kind === "digit" ? "▦5" : "▦", kind === "tensor" ? 81 : kind === "digit" ? 81.1 : 81.2, kind === "digit" ? "semantic" : "exact", [textField("source", kind === "digit" ? "Digit 0–9" : "Values", kind === "digit" ? undefined : "Rows use ; and channels use |"), numField("p1", "Cell size", true, 6), { key: "constructorColor", label: "Colour", input: "color", nullable: true }], (e) => { e.source = kind === "digit" ? "5" : kind === "kernel" ? "-1 0 1; -2 0 2; -1 0 1" : "0 1 0; 1 1 1; 0 1 0"; }, (s, e) => { const source = argString(s.args, 2), cell = argNumber(s.args, 3), color = s.args.length > 4 ? argName(s.args, 4) : null; if (source === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && cell === null) || (s.args.length > 4 && !color)) return false; e.source = source; e.p1 = cell; e.constructorColor = color; e.color = color ?? paint; return true; }, (e) => `${kind}(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${e.p1 === null && e.constructorColor === null ? "" : `, ${num(e.p1 ?? fallback)}`}${e.constructorColor === null ? "" : `, ${e.constructorColor}`});`);
common("convolve", "convolve", "Convolution", "▦∗▦", 81.3, "semantic", [refField("ref", "Input tensor", ["tensor", "digit", "convolve", "pool"]), refField("ref2", "Kernel", ["kernel"]), numField("p1", "Stride", true, 1), numField("p2", "Padding", true, 0), numField("p3", "Bias", true, undefined, .1), { key: "mode", label: "Activation", input: "select", options: ["linear", "relu", "sigmoid", "tanh"] }, numField("p4", "Cell size", true, 6)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => ["tensor", "digit", "convolve", "pool"].includes(x.kind))?.id ?? "input"; e.ref2 = preferReference(doc, undefined, (x) => x.kind === "kernel")?.id ?? "kernel"; e.mode = "linear"; }, (s, e) => { const input = argName(s.args, 1), kernel = argName(s.args, 2), ns = optNums(s, 4, 3), activation = s.args.length > 7 ? argName(s.args, 7) : null, cell = argNumber(s.args, 8); if (!input || !kernel || !ns || s.args.length < 4 || s.args.length > 9 || (s.args.length > 7 && !activation) || (s.args.length > 8 && cell === null)) return false; e.ref = input; e.ref2 = kernel; [e.p1, e.p2, e.p3] = ns; e.mode = activation ?? "linear"; e.p4 = cell; return true; }, (e) => { const needsActivation = e.mode !== "linear" || e.p4 !== null, numeric = needsActivation ? `, ${num(e.p1 ?? 1)}, ${num(e.p2 ?? 0)}, ${num(e.p3 ?? 0)}` : optionalTail([e.p1, e.p2, e.p3], [1, 0, 0]); return `convolve(${e.id}, ${e.ref}, ${e.ref2}, ${pt(e.x, e.y)}${numeric}${needsActivation ? `, ${e.mode}` : ""}${e.p4 === null ? "" : `, ${num(e.p4)}`});`; }, ["tensor", "digit", "kernel", "convolve", "pool"]);
common("pool", "pool", "Pooling", "▦↓", 81.4, "semantic", [refField("ref", "Input tensor", ["tensor", "digit", "convolve", "pool"]), { key: "mode", label: "Pooling", input: "select", options: ["max", "average"] }, numField("p1", "Window", true, 1), numField("p2", "Stride", true, 1), numField("p3", "Padding", true, 0), numField("p4", "Cell size", true, 6)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => ["tensor", "digit", "convolve", "pool"].includes(x.kind))?.id ?? "input"; e.mode = "max"; }, (s, e) => { const input = argName(s.args, 1), mode = argName(s.args, 3), ns = optNums(s, 4, 4); if (!input || !mode || !ns || s.args.length < 4 || s.args.length > 8) return false; e.ref = input; e.mode = mode; [e.p1, e.p2, e.p3, e.p4] = ns; return true; }, (e) => `pool(${e.id}, ${e.ref}, ${pt(e.x, e.y)}, ${e.mode}${optionalTail([e.p1, e.p2, e.p3, e.p4], [2, e.p1 ?? 2, 0, 48])});`, ["tensor", "digit", "convolve", "pool"]);
common("tokenize", "tokenize", "Token sequence", "[tok]", 82, "exact", [textField("source", "Text"), { key: "mode", label: "Tokenizer", input: "select", options: ["word", "authored", "character", "char"] }, numField("p1", "Width", true, 360)], (e) => { e.source = "the model learns"; e.mode = "word"; }, (s, e) => { const source = argString(s.args, 2), mode = s.args.length > 3 ? argName(s.args, 3) : null, width = argNumber(s.args, 4); if (source === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && !mode) || (s.args.length > 4 && width === null)) return false; e.source = source; e.mode = mode ?? "word"; e.p1 = width; return true; }, (e) => `tokenize(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${e.mode === "word" && e.p1 === null ? "" : `, ${e.mode}`}${e.p1 === null ? "" : `, ${num(e.p1)}`});`);
common("embedding", "embedding", "Token embedding", "tok→v", 82.1, "semantic", [refField("ref", "Tokens", ["tokenize"]), textField("source", "Vectors", "Explicit rows or seeded D S"), { key: "mode", label: "Position", input: "select", options: ["sinusoidal", "sine", "none"] }, numField("p1", "Width", true, 300), numField("p2", "Height", true, 180)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => x.kind === "tokenize")?.id ?? "tokens"; e.source = "seeded 6 37"; e.mode = "sinusoidal"; }, (s, e) => { const ref = argName(s.args, 1), source = argString(s.args, 3), mode = s.args.length > 4 ? argName(s.args, 4) : null, ns = optNums(s, 5, 2); if (!ref || source === null || !ns || s.args.length < 4 || s.args.length > 7 || (s.args.length > 4 && !mode)) return false; e.ref = ref; e.source = source; e.mode = mode ?? "sinusoidal"; [e.p1, e.p2] = ns; return true; }, (e) => `embedding(${e.id}, ${e.ref}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${e.mode === "sinusoidal" && e.p1 === null && e.p2 === null ? "" : `, ${e.mode}`}${e.p1 === null && e.p2 === null ? "" : `, ${num(e.p1 ?? 1040)}`}${e.p2 === null ? "" : `, ${num(e.p2)}`});`, ["tokenize"]);
common("transformer", "transformer", "Transformer block", "T", 82.2, "semantic", [refField("ref", "Embedding", ["embedding"]), textField("source", "Configuration", "heads, mask, mlp, activation, norm, dropout, mode, seed"), numField("p1", "Width", true, 300), numField("p2", "Height", true, 180)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => x.kind === "embedding")?.id ?? "embedding"; e.source = "heads=2 mask=causal mlp=12 activation=gelu norm=pre dropout=0 mode=inference seed=41"; }, (s, e) => { const ref = argName(s.args, 1), source = argString(s.args, 3), ns = optNums(s, 4, 2); if (!ref || source === null || !ns || s.args.length < 4 || s.args.length > 6) return false; e.ref = ref; e.source = source; [e.p1, e.p2] = ns; return true; }, (e) => `transformer(${e.id}, ${e.ref}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${optionalTail([e.p1, e.p2], [1120, 520])});`, ["embedding"]);
common("logits", "logits", "Logits and probabilities", "p(tok)", 82.3, "semantic", [refField("ref", "Transformer", ["transformer"]), { key: "p1", label: "Token (1-based)", input: "number", min: 1, step: 1 }, textField("source", "Candidate labels", "Separate labels with |"), numField("p2", "Temperature", true, .001, .05), numField("p3", "Width", true, 300), numField("p4", "Height", true, 180), numField("p5", "Seed", true, 0)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => x.kind === "transformer")?.id ?? "transformer"; e.p1 = 1; e.source = "yes | no | maybe"; }, (s, e) => { const ref = argName(s.args, 1), token = argNumber(s.args, 2), labels = argString(s.args, 4), ns = optNums(s, 5, 4); if (!ref || token === null || labels === null || !ns || s.args.length < 5 || s.args.length > 9) return false; e.ref = ref; e.p1 = token; e.source = labels; [e.p2, e.p3, e.p4, e.p5] = ns; return true; }, (e) => `logits(${e.id}, ${e.ref}, ${num(e.p1 ?? 1)}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${optionalTail([e.p2, e.p3, e.p4, e.p5], [1, 760, 440, 73])});`, ["transformer"]);
common("attention", "attention", "Self-attention", "QKV", 82.4, "semantic", [textField("source", "Tokens", "Separate tokens with |"), textField("source2", "Embedding rows"), numField("p1", "Width", true, 300), numField("p2", "Height", true, 180), numField("p3", "Seed", true, 0)], (e) => { e.source = "the | model | learns"; e.source2 = "1 0 0; 0 1 0; 0 0 1"; }, (s, e) => { const tokens = argString(s.args, 2), embeddings = argString(s.args, 3), ns = optNums(s, 4, 3); if (tokens === null || embeddings === null || !ns || s.args.length < 4 || s.args.length > 7) return false; e.source = tokens; e.source2 = embeddings; [e.p1, e.p2, e.p3] = ns; return true; }, (e) => `attention(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.source)}", "${escapeString(e.source2)}"${optionalTail([e.p1, e.p2, e.p3], [900, 430, 17])});`);
common("topk", "topk", "Attention top-k", "Top K", 82.5, "semantic", [refField("ref", "Attention", ["attention"]), { key: "p1", label: "Token (1-based)", input: "number", min: 1, step: 1 }, textField("source", "Candidate labels", "Separate labels with |"), numField("p2", "K", true, 1), numField("p3", "Width", true, 200), numField("p4", "Height", true, 120), numField("p5", "Seed", true, 0)], (e, doc, selected) => { e.ref = preferReference(doc, selected, (x) => x.kind === "attention")?.id ?? "attention"; e.p1 = 1; e.source = "one | two | three | four"; }, (s, e) => { const ref = argName(s.args, 1), token = argNumber(s.args, 2), labels = argString(s.args, 4), ns = optNums(s, 5, 4); if (!ref || token === null || labels === null || !ns || s.args.length < 5 || s.args.length > 9) return false; e.ref = ref; e.p1 = token; e.source = labels; [e.p2, e.p3, e.p4, e.p5] = ns; return true; }, (e) => `topk(${e.id}, ${e.ref}, ${num(e.p1 ?? 1)}, ${pt(e.x, e.y)}, "${escapeString(e.source)}"${optionalTail([e.p2, e.p3, e.p4, e.p5], [3, 420, 230, 29])});`, ["attention"]);
