// Physics kit: editable simulation declarations and dependent analysis panels.
// Canvas uses bounded design-state diagrams; native Preview owns integration.

import { argName, argNumber, argPoint, argString, escapeString, num, pt } from "../args.js";
import { registerEntity, type Box, type FieldSpec, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import type { OpticsPrimitive } from "./optics.js";
import type { PhysicsEntity, PhysicsKind, PhysicsPanel, Point, VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

export type PhysicsPrimitive = OpticsPrimitive;
export interface PhysicsGeometry { primitives: PhysicsPrimitive[]; note: string }
type Prop = "p1"|"p2"|"p3"|"p4"|"p5"|"p6"|"p7"|"p8"|"source"|"source2"|"domain";
type ArgSpec = { prop: Prop; type: "num"|"str"|"point"; label: string; required?: boolean; default: number|string|Point };
interface SimSpec { kind: PhysicsKind; label: string; icon: string; order: number; centerRequired?: boolean; args: ArgSpec[] }
const n=(prop:Prop,label:string,required=false,def=1):ArgSpec=>({prop,type:"num",label,required,default:def});
const s=(prop:Prop,label:string,required=false,def=""):ArgSpec=>({prop,type:"str",label,required,default:def});
const q=(prop:Prop,label:string,required=false,def:Point={x:0,y:Math.PI*2}):ArgSpec=>({prop,type:"point",label,required,default:def});

const specs:SimSpec[]=[
  {kind:"freekick",label:"Free kick",icon:"⚽↗",order:100,centerRequired:true,args:[n("p1","Speed",true,28),n("p2","Launch angle °",true,22),n("p3","Spin",true,8),n("p4","Scale",false,12),n("p5","Steps",false,900)]},
  {kind:"pendulum",label:"Pendulum",icon:"⌁●",order:100.1,args:[n("p1","Length",false,1.5),n("p2","Initial angle °",false,45),n("p3","Pixels per unit",false,160),n("p4","Damping",false,0)]},
  {kind:"spring",label:"Spring mass",icon:"≈■",order:100.2,args:[n("p1","Stiffness",false,4),n("p2","Initial displacement",false,1),n("p3","Pixels per unit",false,120),n("p4","Damping",false,0),n("p5","Initial velocity",false,0)]},
  {kind:"doublependulum",label:"Double pendulum",icon:"⌁●●",order:100.3,args:[n("p1","Angle 1 °",false,120),n("p2","Angle 2 °",false,-10),n("p3","Pixels per unit",false,120)]},
  {kind:"springpendulum",label:"Spring pendulum",icon:"≈●",order:100.4,args:[n("p1","Initial angle °",false,35),n("p2","Initial stretch",false,.25),n("p3","Pixels per unit",false,120),n("p4","Damping",false,.02)]},
  {kind:"kapitza",label:"Kapitza pendulum",icon:"↕●",order:100.5,args:[n("p1","Initial angle °",false,170),n("p2","Vibration amplitude",false,.15),n("p3","Pixels per unit",false,150)]},
  {kind:"cartpendulum",label:"Cart pendulum",icon:"▭⌁",order:100.6,args:[n("p1","Initial angle °",false,25),n("p2","Pixels per unit",false,130)]},
  {kind:"comparependulum",label:"Chaos comparison",icon:"⌁●⌁●",order:100.7,args:[n("p1","Initial angle °",false,120),n("p2","Pixels per unit",false,110)]},
  {kind:"verticalspring",label:"Vertical spring",icon:"≋\n■",order:101,args:[n("p1","Initial stretch",false,.4),n("p2","Pixels per unit",false,110),n("p3","Damping",false,.03)]},
  {kind:"springincline",label:"Spring on incline",icon:"≈■╱",order:101.1,args:[n("p1","Incline angle °",false,28),n("p2","Pixels per unit",false,100),n("p3","Damping",false,.03)]},
  {kind:"bungee",label:"Bungee",icon:"│≈●",order:101.2,args:[n("p1","Pixels per unit",false,80),n("p2","Damping",false,.08)]},
  {kind:"resonance",label:"Driven resonance",icon:"≈■↔",order:101.3,args:[n("p1","Drive frequency",false,2),n("p2","Pixels per unit",false,100),n("p3","Damping",false,.08)]},
  {kind:"doublespring",label:"Coupled springs",icon:"≈■≈■",order:101.4,args:[n("p1","Pixels per unit",false,90)]},
  {kind:"seriesparallel",label:"Series vs parallel",icon:"≈∥≈",order:101.5,args:[n("p1","Pixels per unit",false,90)]},
  {kind:"carsuspension",label:"Car suspension",icon:"▱◉",order:101.6,args:[n("p1","Pixels per unit",false,80)]},
  {kind:"piston",label:"Piston",icon:"◉┫",order:101.7,args:[n("p1","RPM",false,120),n("p2","Pixels per unit",false,100)]},
  {kind:"molecule",label:"Molecule",icon:"●≈●",order:102,args:[n("p1","Atoms",false,5),n("p2","Pixels per unit",false,80)]},
  {kind:"robotarm",label:"Robot arm",icon:"⌁⌁◎",order:102.1,args:[n("p1","Target mode",false,1),n("p2","Pixels per unit",false,100)]},
  {kind:"pulley",label:"Atwood pulley",icon:"◯⇅",order:102.2,args:[n("p1","Mass 1",false,2),n("p2","Mass 2",false,3),n("p3","Pixels per unit",false,80)]},
  {kind:"pulleyscale",label:"Pulley scale",icon:"◯⇅▣",order:102.3,args:[n("p1","Mass 1",false,2),n("p2","Mass 2",false,3),n("p3","Pixels per unit",false,80)]},
  {kind:"blocktackle",label:"Block and tackle",icon:"◯◯⇅",order:102.4,args:[n("p1","Load",false,100),n("p2","Effort",false,25),n("p3","Supporting strands",false,4),n("p4","Pixels per unit",false,70)]},
  {kind:"compoundpulley",label:"Compound pulley",icon:"◯◉◯",order:102.5,args:[n("p1","Mass A",false,4),n("p2","Mass B",false,2),n("p3","Mass C",false,2),n("p4","Pixels per unit",false,70)]},
  {kind:"ramp",label:"Friction ramp",icon:"■╱",order:103,args:[n("p1","Incline angle °",false,28),n("p2","Mass",false,2),n("p3","Applied force",false,0),n("p4","Pixels per unit",false,90)]},
  {kind:"dropmass",label:"Drop onto spring",icon:"■↓≈",order:103.1,args:[n("p1","Drop height",false,2),n("p2","Pixels per unit",false,90)]},
  {kind:"inclinepulley",label:"Incline pulley",icon:"■╱◯",order:103.2,args:[n("p1","Incline angle °",false,28),n("p2","Mass 1",false,2),n("p3","Mass 2",false,2.5),n("p4","Pixels per unit",false,80)]},
  {kind:"doubleincline",label:"Double incline",icon:"■╱╲■",order:103.3,args:[n("p1","Angle 1 °",false,30),n("p2","Angle 2 °",false,35),n("p3","Mass 1",false,2),n("p4","Mass 2",false,2),n("p5","Pixels per unit",false,75)]},
  {kind:"inclinebumper",label:"Incline spring bumper",icon:"■╲≈",order:103.4,args:[n("p1","Incline angle °",false,28),n("p2","Mass",false,2),n("p3","Stiffness",false,8),n("p4","Pixels per unit",false,80)]},
  {kind:"springchain",label:"Incline spring chain",icon:"■≈■≈■",order:103.5,args:[n("p1","Incline angle °",false,28),n("p2","Pixels per unit",false,70)]},
  {kind:"looptrack",label:"Loop-the-loop",icon:"↘○",order:104,args:[n("p1","Loop radius",false,1.5),n("p2","Start height",false,4),n("p3","Pixels per unit",false,80)]},
  {kind:"collideblocks",label:"Colliding blocks",icon:"■→←■",order:104.1,args:[n("p1","Mass 1",false,2),n("p2","Mass 2",false,3),n("p3","Restitution",false,1),n("p4","Pixels per unit",false,80)]},
  {kind:"bulletblock",label:"Bullet into block",icon:"•→■",order:104.2,args:[n("p1","Bullet mass",false,.02),n("p2","Bullet speed",false,120),n("p3","Block mass",false,2),n("p4","Pixels per unit",false,80)]},
  {kind:"newtonscradle",label:"Newton's cradle",icon:"●●●●●",order:104.3,args:[n("p1","Balls",false,5),n("p2","Pulled balls",false,1)]},
  {kind:"gas",label:"Particle gas",icon:"⁙□",order:105,args:[n("p1","Box width",false,620),n("p2","Box height",false,360),n("p3","Particle count",false,80),s("source","Simulation spec",false,"temperature=1 radius=5 mass=1 scale=50 dt=0.01 steps=900 seed=7 start=maxwell")]},
  {kind:"dominos",label:"Domino wave",icon:"▯▯▯",order:105.1,args:[n("p1","Count",false,18),n("p2","Height mm",false,45),n("p3","Thickness mm",false,7.5438),n("p4","Spacing mm",false,9.38),n("p5","Pixels per mm",false,2),n("p6","Transfer",false,.82),n("p7","Initial push",false,2.2)]},
  {kind:"dominopath",label:"Domino path",icon:"∿▯",order:105.2,centerRequired:true,args:[n("p1","X scale",true,220),n("p2","Y scale",true,150),s("source","x(t)",true,"cos(t)"),s("source2","y(t)",true,"sin(t)"),n("p3","Count",false,40),q("domain","t domain",false,{x:0,y:Math.PI*2}),n("p4","Height mm",false,45),n("p5","Thickness mm",false,7.5438),n("p6","Pixels per mm",false,2),n("p7","Transfer",false,.82),n("p8","Initial push",false,2.2)]},
  {kind:"stringwave",label:"String wave",icon:"〰",order:105.3,args:[n("p1","Width",false,720),n("p2","Amplitude",false,100),n("p3","Pluck position",false,.3)]},
  {kind:"raft",label:"Person on raft",icon:"♟▰",order:105.4,args:[n("p1","Person mass",false,70),n("p2","Raft mass",false,140),n("p3","Pixels per unit",false,70)]},
  {kind:"brachistochrone",label:"Brachistochrone race",icon:"⌣●",order:105.5,args:[n("p1","Pixels per unit",false,90)]},
];
export const PHYSICS_KINDS = specs.map(spec=>spec.kind) as readonly PhysicsKind[];
const specByKind=new Map(specs.map(spec=>[spec.kind,spec]));

const tag=(entity:PhysicsEntity,...more:string[])=>[entity.id,`${entity.id}.parts`,...more];
const line=(e:PhysicsEntity,id:string,a:Point,b:Point,color="dim",width=2,opacity=1,more:string[]=[]):PhysicsPrimitive=>({id:`${e.id}.${id}`,kind:"line",from:a,to:b,color,width,opacity,tags:tag(e,...more)});
const circle=(e:PhysicsEntity,id:string,x:number,y:number,radius:number,color="cyan",more:string[]=[]):PhysicsPrimitive=>({id:`${e.id}.${id}`,kind:"circle",x,y,radius,color,opacity:1,fill:true,tags:tag(e,...more)});
const rect=(e:PhysicsEntity,id:string,x:number,y:number,width:number,height:number,color="cyan",opacity=.25,outline=true):PhysicsPrimitive=>({id:`${e.id}.${id}`,kind:"rect",x,y,width,height,color,opacity,outline,tags:tag(e)});
const path=(e:PhysicsEntity,id:string,points:Point[],color="cyan",more:string[]=[]):PhysicsPrimitive=>({id:`${e.id}.${id}`,kind:"polyline",points,color,width:2.5,opacity:1,tags:tag(e,...more)});
const text=(e:PhysicsEntity,id:string,value:string,x:number,y:number,color="dim",size=15):PhysicsPrimitive=>({id:`${e.id}.${id}`,kind:"text",x,y,text:value,color,size,opacity:1,tags:tag(e)});
function coil(x1:number,y1:number,x2:number,y2:number,turns=9):Point[]{return Array.from({length:turns*2+1},(_v,i)=>{const t=i/(turns*2),wiggle=i===0||i===turns*2?0:(i%2?1:-1)*9;return{x:x1+(x2-x1)*t,y:y1+(y2-y1)*t+wiggle};});}

export function physicsGeometry(e:PhysicsEntity):PhysicsGeometry{
  const out:PhysicsPrimitive[]=[], x=e.x,y=e.y, k=e.kind;
  const pendulum=["pendulum","doublependulum","springpendulum","kapitza","cartpendulum","comparependulum"].includes(k), springs=["spring","verticalspring","springincline","resonance","doublespring","seriesparallel","springchain","dropmass","inclinebumper"].includes(k), pulleys=["pulley","pulleyscale","blocktackle","compoundpulley","inclinepulley","doubleincline"].includes(k), collisions=["collideblocks","bulletblock","newtonscradle"].includes(k);
  if(pendulum){const pivot={x,y:y-120},a=(e.p1??35)*Math.PI/180,bob={x:x+Math.sin(a)*145,y:pivot.y+Math.cos(a)*145};out.push(circle(e,"pivot",pivot.x,pivot.y,7,"gold"),line(e,"rod",pivot,bob,"fg",3),circle(e,"bob",bob.x,bob.y,18,"cyan"),path(e,"path",Array.from({length:31},(_v,i)=>{const q=-.8+1.6*i/30;return{x:pivot.x+Math.sin(q)*145,y:pivot.y+Math.cos(q)*145};}),"dim"));if(k==="doublependulum"||k==="comparependulum"){const bob2={x:bob.x+Math.sin((e.p2??-10)*Math.PI/180)*110,y:bob.y+Math.cos((e.p2??-10)*Math.PI/180)*110};out.push(line(e,"rod2",bob,bob2,"magenta",3),circle(e,"bob2",bob2.x,bob2.y,16,"magenta"));}if(k==="cartpendulum")out.push(rect(e,"cart",x-80,pivot.y-24,160,48,"fg",.15,true));}
  else if(springs){out.push(rect(e,"wall",x-290,y-80,24,160,"dim",.25,true),path(e,"spring",coil(x-266,y,x+40,y),"cyan"),rect(e,"mass",x+40,y-45,90,90,"gold",.35,true),line(e,"guide",{x:x-290,y:y+58},{x:x+260,y:y+58},"dim",1));if(["doublespring","springchain"].includes(k)){out.push(path(e,"spring2",coil(x+130,y,x+230,y),"magenta"),rect(e,"mass2",x+230,y-38,76,76,"cyan",.3,true));}}
  else if(pulleys){out.push(circle(e,"pulley",x,y-105,52,"gold"),line(e,"ropeL",{x:x-52,y:y-105},{x:x-52,y:y+120},"fg",3),line(e,"ropeR",{x:x+52,y:y-105},{x:x+52,y:y+120},"fg",3),rect(e,"massA",x-88,y+120,72,72,"cyan",.3,true),rect(e,"massB",x+16,y+120,72,72,"magenta",.3,true));if(k==="blocktackle")out.push(circle(e,"movable",x,y+55,42,"cyan"));}
  else if(["ramp","springincline","inclinepulley","doubleincline","inclinebumper","springchain"].includes(k)){out.push(path(e,"incline",[{x:x-280,y:y+140},{x:x+260,y:y+140},{x:x+260,y:y-130}],"dim"),rect(e,"block",x+40,y-2,82,58,"cyan",.35,true),line(e,"forces",{x:x+80,y:y+28},{x:x+80,y:y+125},"gold",3));}
  else if(collisions){out.push(line(e,"track",{x:x-310,y:y+72},{x:x+310,y:y+72},"dim",3));const count=k==="newtonscradle"?Math.max(2,Math.min(12,Math.round(e.p1??5))):2;for(let i=0;i<count;i++){const px=x+(i-(count-1)/2)*48;out.push(k==="newtonscradle"?circle(e,`ball${i}`,px,y+25,20,i===0?"gold":"cyan",[`${e.id}.balls`]):rect(e,`block${i+1}`,px-55,y,110,70,i?"magenta":"cyan",.35,true));}}
  else if(k==="gas"){const w=Math.max(180,e.p1??620),h=Math.max(120,e.p2??360),count=Math.min(80,Math.max(1,Math.round(e.p3??80)));out.push(rect(e,"box",x-w/2,y-h/2,w,h,"dim",0,true));for(let i=0;i<count;i++){const px=x-w*.44+((i*73)%100)/100*w*.88,py=y-h*.42+((i*47)%100)/100*h*.84;out.push(circle(e,`p${i}`,px,py,4+(i%3),i%3===0?"magenta":"cyan",[`${e.id}.particles`]));}}
  else if(k==="dominos"||k==="dominopath"){const count=Math.min(40,Math.max(2,Math.round(e.p1??18)));out.push(line(e,"ground",{x:x-310,y:y+100},{x:x+310,y:y+100},"dim",2));for(let i=0;i<count;i++){const px=x-285+i*570/(count-1),tilt=i<4?i*.16:0;out.push(path(e,`d${i}`,[{x:px,y:y+100},{x:px+Math.sin(tilt)*58,y:y+100-Math.cos(tilt)*58}],i<4?"gold":"cyan",[`${e.id}.dominos`]));}}
  else if(k==="stringwave"){out.push(path(e,"string0",Array.from({length:101},(_v,i)=>{const t=i/100;return{x:x-330+t*660,y:y-Math.sin(t*Math.PI)*Math.sin(t*Math.PI*3)*90};}),"cyan"),circle(e,"anchorP",x-330,y,7,"gold"),circle(e,"anchorS",x+330,y,7,"gold"));}
  else if(k==="freekick"){const pts=Array.from({length:61},(_v,i)=>{const t=i/60;return{x:x-280+t*570,y:y+120-360*t*(1-t)-Math.sin(t*Math.PI)*70};});out.push(path(e,"path",pts,"gold"),circle(e,"ball",pts[0].x,pts[0].y,15,"fg"),rect(e,"target",x+250,y-30,90,150,"cyan",0,true));}
  else if(k==="looptrack"){out.push(path(e,"track",[{x:x-300,y:y-130},{x:x-150,y:y+120},{x:x+10,y:y+120},...Array.from({length:41},(_v,i)=>{const a=Math.PI/2-i*Math.PI*2/40;return{x:x+120+Math.cos(a)*110,y:y+10+Math.sin(a)*110};})],"cyan"),circle(e,"ball",x-260,y-72,14,"gold"));}
  else if(k==="brachistochrone"){for(let i=0;i<4;i++){const yy=y-100+i*65;out.push(path(e,`path${String.fromCharCode(65+i)}`,Array.from({length:41},(_v,j)=>{const t=j/40;return{x:x-300+t*600,y:yy+(i===0?t:i===1?t*t:i===2?Math.sin(t*Math.PI/2):1-Math.cos(t*Math.PI/2))*120};}),["cyan","magenta","gold","lime"][i]),circle(e,`bead_${i}`,x-300,yy,7,["cyan","magenta","gold","lime"][i]));}}
  else {out.push(rect(e,"body",x-130,y-70,260,140,"cyan",.18,true),circle(e,"hub",x,y,28,"gold"),line(e,"arm",{x,y},{x:x+160,y:y-80},"magenta",4),text(e,"label",specByKind.get(k)?.label??k,x,y+115,"fg",18));}
  for(const [name,panel] of [["phase",e.phase],["well",e.well],["time",e.timegraph],["energy",e.energygraph]] as const)if(panel){const size=panel.size??240;out.push(rect(e,name,panel.x-size/2,panel.y-size*.34,size,size*.68,"dim",0,true),path(e,`${name}.curve`,Array.from({length:51},(_v,i)=>{const t=i/50;return{x:panel.x-size*.42+t*size*.84,y:panel.y+Math.sin(t*Math.PI*4)*(name==="well"?1-t:.65)*size*.22};}),name==="energy"?"gold":"cyan"));}
  if(e.speeds){const w=e.speeds.p1??420,h=e.speeds.p2??220;out.push(line(e,"speeds.axis",{x:e.speeds.x-w/2,y:e.speeds.y+h/2},{x:e.speeds.x+w/2,y:e.speeds.y+h/2},"dim",2));for(let i=0;i<Math.min(24,Math.round(e.speeds.p3??12));i++){const bh=Math.sin((i+1)/25*Math.PI)*h*.75;out.push(rect(e,`speeds.b${i}`,e.speeds.x-w/2+i*w/24,e.speeds.y+h/2-bh,w/26,bh,"cyan",.55,false));}}
  return{primitives:out,note:`Design state only · Preview runs the native ${k} simulation`};
}

function base(id:string,kind:PhysicsKind,x:number,y:number):PhysicsEntity{return{...baseEntity(id,"cyan"),nativePaint:true,kind,x,y,source:"",source2:"",domain:null,p1:null,p2:null,p3:null,p4:null,p5:null,p6:null,p7:null,p8:null,species:[],rules:[],speeds:null,phase:null,well:null,timegraph:null,energygraph:null,childStyles:{}};}
const move=(e:PhysicsEntity,dx:number,dy:number)=>{e.x+=dx;e.y+=dy;};
function childStyle(e:PhysicsEntity,ref:string):VirtualChildStyle{return e.childStyles[ref]??(e.childStyles[ref]={});}
function applyChild(e:PhysicsEntity,ref:string,stmt:CallStatement):boolean{const style=childStyle(e,ref);if(stmt.name==="color"){const v=argName(stmt.args,1);if(!v)return false;style.color=v;return true;}if(stmt.name==="opacity"){const v=argNumber(stmt.args,1);if(v===null)return false;style.opacity=v;return true;}if(stmt.name==="hidden"){style.reveal=argName(stmt.args,1)==="center"?"grow":"fade";return true;}if(stmt.name==="untraced"){style.untraced=true;return true;}return false;}
function childLines(styles:Record<string,VirtualChildStyle>):string[]{return Object.entries(styles).flatMap(([ref,style])=>[...(style.color?[`color(${ref}, ${style.color});`]:[]),...(style.opacity!==undefined?[`opacity(${ref}, ${num(style.opacity)});`]:[]),...(style.reveal?[`hidden(${ref}${style.reveal==="grow"?", center":""});`]:[]),...(style.untraced?[`untraced(${ref});`]:[])]);}
function get(e:PhysicsEntity,prop:Prop):unknown{return e[prop as keyof PhysicsEntity];}
function set(e:PhysicsEntity,prop:Prop,value:unknown){(e as unknown as Record<string,unknown>)[prop]=value;}
function parseEntity(spec:SimSpec,stmt:CallStatement):PhysicsEntity|null{const id=argName(stmt.args,0);if(!id)return null;let cursor=1;let at:Point={x:640,y:360};if(stmt.args.length>1){const p=argPoint(stmt.args,1);if(!p)return null;at=p;cursor=2;}else if(spec.centerRequired)return null;const e=base(id,spec.kind,at.x,at.y);for(const arg of spec.args){if(cursor>=stmt.args.length){if(arg.required)return null;set(e,arg.prop,null);continue;}const value=arg.type==="num"?argNumber(stmt.args,cursor):arg.type==="str"?argString(stmt.args,cursor):argPoint(stmt.args,cursor);if(value===null)return null;set(e,arg.prop,value);cursor++;}return cursor===stmt.args.length?e:null;}
function renderArg(arg:ArgSpec,value:unknown):string{return arg.type==="num"?num(value as number):arg.type==="str"?`"${escapeString(value as string)}"`:pt((value as Point).x,(value as Point).y);}
function ctorLine(e:PhysicsEntity):string{const spec=specByKind.get(e.kind)!;let last=spec.args.length-1;while(last>=0&&!spec.args[last].required&&get(e,spec.args[last].prop)===null)last--;const tail=spec.args.slice(0,last+1).map(arg=>renderArg(arg,get(e,arg.prop)??arg.default));return`${e.kind}(${e.id}, ${pt(e.x,e.y)}${tail.length?`, ${tail.join(", ")}`:""});`;}
const panelLine=(name:string,id:string,p:PhysicsPanel)=>`${name}(${id}, ${pt(p.x,p.y)}${name==="speeds"?`, ${num(p.p1??420)}, ${num(p.p2??220)}, ${num(p.p3??12)}, ${num(p.p4??9)}${p.size===null?"":`, ${num(p.size)}`}`:p.size===null?"":`, ${num(p.size)}`});`;
function extraLines(e:PhysicsEntity):string[]{return[...e.species.map(v=>`species(${e.id}, ${v.name}${v.weight===null?`${v.color?`, ${v.color}`:""}`:`, ${num(v.weight)}${v.color?`, ${v.color}`:""}`});`),...e.rules.map(v=>`rule(${e.id}, "${escapeString(v)}");`),...(e.speeds?[panelLine("speeds",e.id,e.speeds)]:[]),...(e.phase?[panelLine("phase",e.id,e.phase)]:[]),...(e.well?[panelLine("well",e.id,e.well)]:[]),...(e.timegraph?[panelLine("timegraph",e.id,e.timegraph)]:[]),...(e.energygraph?[panelLine("energygraph",e.id,e.energygraph)]:[]),...childLines(e.childStyles)];}
function panel(stmt:CallStatement):PhysicsPanel|null{const at=argPoint(stmt.args,1),size=argNumber(stmt.args,2);return at&&stmt.args.length<=3&&(stmt.args.length<3||size!==null)?{x:at.x,y:at.y,size}:null;}
const modifiers={
  species(e:PhysicsEntity,stmt:CallStatement){if(e.kind!=="gas")return false;const name=argName(stmt.args,1),weight=argNumber(stmt.args,2),shortColor=argName(stmt.args,2),color=argName(stmt.args,3);if(!name||stmt.args.length<2||stmt.args.length>4||(stmt.args.length===4&&(weight===null||!color))||(stmt.args.length===3&&weight===null&&!shortColor))return false;e.species.push({name,weight:stmt.args.length===3&&weight===null?null:weight,color:stmt.args.length===3&&weight===null?shortColor:color});return true;},
  rule(e:PhysicsEntity,stmt:CallStatement){if(e.kind!=="gas")return false;const value=argString(stmt.args,1);if(value===null||stmt.args.length!==2)return false;e.rules.push(value);return true;},
  speeds(e:PhysicsEntity,stmt:CallStatement){if(e.kind!=="gas")return false;const at=argPoint(stmt.args,1),values=[argNumber(stmt.args,2),argNumber(stmt.args,3),argNumber(stmt.args,4),argNumber(stmt.args,5),argNumber(stmt.args,6)];if(!at||stmt.args.length>7||values.some((v,i)=>stmt.args.length>i+2&&v===null))return false;e.speeds={x:at.x,y:at.y,p1:values[0],p2:values[1],p3:values[2],p4:values[3],size:values[4]};return true;},
  phase(e:PhysicsEntity,stmt:CallStatement){const value=panel(stmt);if(!value)return false;e.phase=value;return true;},well(e:PhysicsEntity,stmt:CallStatement){const value=panel(stmt);if(!value)return false;e.well=value;return true;},timegraph(e:PhysicsEntity,stmt:CallStatement){const value=panel(stmt);if(!value)return false;e.timegraph=value;return true;},energygraph(e:PhysicsEntity,stmt:CallStatement){const value=panel(stmt);if(!value)return false;e.energygraph=value;return true;},
};
function refs(e:PhysicsEntity):string[]{const common=["parts","overlays","path","body","pivot","rod","rod1","rod2","bob","bob1","bob2","spring","spring1","spring2","mass","mass1","mass2","wall","ground","track","ball","block","block1","block2","pulley","ropeL","ropeR","forces","phase","well","time","energy","particles","dominos","rays","speeds","speeds.axis","speeds.mb","speeds.bars","sensor","target","label"].map(v=>`${e.id}.${v}`),indexed=Array.from({length:120},(_v,i)=>[`${e.id}.p${i}`,`${e.id}.d${i}`,`${e.id}.ball${i}`,`${e.id}.atom${i}`,`${e.id}.bond${i}`,`${e.id}.seg${i}`,`${e.id}.strand${i}`,`${e.id}.speeds.b${i}`]).flat();return[...common,...indexed,...physicsGeometry(e).primitives.flatMap(v=>[v.id,...v.tags])];}
function fields(spec:SimSpec):FieldSpec[]{return spec.args.map(arg=>({key:arg.prop,label:arg.label,input:arg.type==="num"?"number":arg.type==="point"?"point":"textarea",nullable:!arg.required,step:arg.type==="num"?.1:undefined,hint:arg.type==="str"&&arg.prop==="source"&&spec.kind==="gas"?"key=value simulation settings":undefined}));}
for(const spec of specs)registerEntity<PhysicsEntity>({kind:spec.kind,ctor:spec.kind,group:"Physics",label:spec.label,icon:spec.icon,order:spec.order,fidelity:"semantic",hint:"Editable initial conditions and bounded design state; Preview owns simulation",anchorArgIndex:1,create(id,x,y){const e=base(id,spec.kind,x,y);for(const arg of spec.args)if(arg.required)set(e,arg.prop,arg.default);return e;},parseArgs(stmt){return parseEntity(spec,stmt);},ctorLine,extraLines,modifiers,anchor:e=>({x:e.x,y:e.y}),translate:move,bounds(e):Box{return{x:e.x-360,y:e.y-240,width:720,height:480};},handles:()=>[],dragHandle(){},fields:fields(spec),references:()=>[],replaceReference(){},referenceIds:refs,storyTargets(e){return physicsGeometry(e).primitives.map((primitive):StoryTargetSpec=>({id:primitive.id,label:primitive.id,kind:primitive.kind==="circle"?"dot":primitive.kind==="text"?"text":primitive.kind==="rect"||primitive.kind==="polygon"?"rect":"line"}));},applyReferenceModifier:applyChild});
