import { argName, argNumber, argPoint, num, pt } from "../args.js";
import { registerEntity, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import type { LiveHistogramEntity, VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

function childStyle(e:LiveHistogramEntity,ref:string):VirtualChildStyle{return e.childStyles[ref]??(e.childStyles[ref]={});}
function applyChild(e:LiveHistogramEntity,ref:string,stmt:CallStatement):boolean{const s=childStyle(e,ref);if(stmt.name==="color"){const v=argName(stmt.args,1);if(!v)return false;s.color=v;return true;}if(stmt.name==="opacity"){const v=argNumber(stmt.args,1);if(v===null)return false;s.opacity=v;return true;}if(stmt.name==="hidden"){s.reveal="fade";return true;}return false;}
function childLines(styles:Record<string,VirtualChildStyle>):string[]{return Object.entries(styles).flatMap(([ref,s])=>[...(s.color?[`color(${ref}, ${s.color});`]:[]),...(s.opacity!==undefined?[`opacity(${ref}, ${num(s.opacity)});`]:[]),...(s.reveal?[`hidden(${ref});`]:[])]);}
registerEntity<LiveHistogramEntity>({kind:"livehistogram",ctor:"livehistogram",group:"Process",label:"Live histogram",icon:"▂▅▇",order:110,fidelity:"semantic",hint:"Initially empty measurement view driven by Stream, Emit, Branch, Collect, or Observe",anchorArgIndex:1,
  create(id,x,y){return{...baseEntity(id,"cyan"),nativePaint:true,kind:"livehistogram",x,y,min:0,max:1,bins:10,width:520,height:220,constructorColor:"cyan",childStyles:{}};},
  parseArgs(stmt){const id=argName(stmt.args,0),at=argPoint(stmt.args,1),min=argNumber(stmt.args,2),max=argNumber(stmt.args,3),bins=argNumber(stmt.args,4),width=argNumber(stmt.args,5),height=argNumber(stmt.args,6),color=argName(stmt.args,7);if(!id||!at||min===null||max===null||bins===null||stmt.args.length<5||stmt.args.length>8||(stmt.args.length>5&&width===null)||(stmt.args.length>6&&height===null)||(stmt.args.length>7&&!color))return null;return{...baseEntity(id,color??"cyan"),nativePaint:true,kind:"livehistogram",x:at.x,y:at.y,min,max,bins:Math.round(bins),width:width??520,height:height??220,constructorColor:color??"cyan",childStyles:{}};},
  ctorLine:e=>`livehistogram(${e.id}, ${pt(e.x,e.y)}, ${num(e.min)}, ${num(e.max)}, ${num(e.bins)}, ${num(e.width)}, ${num(e.height)}, ${e.constructorColor});`,extraLines:e=>childLines(e.childStyles),modifiers:{},anchor:e=>({x:e.x,y:e.y}),translate(e,dx,dy){e.x+=dx;e.y+=dy;},bounds:e=>({x:e.x-e.width/2,y:e.y-e.height/2-34,width:e.width,height:e.height+62}),handles:e=>[{name:"size",x:e.x+e.width/2,y:e.y+e.height/2}],dragHandle(e,_h,x,y){e.width=Math.max(21,Math.abs(x-e.x)*2);e.height=Math.max(21,Math.abs(y-e.y)*2);},fields:[{key:"min",label:"Range minimum",input:"number",step:.1},{key:"max",label:"Range maximum",input:"number",step:.1},{key:"bins",label:"Bins",input:"number",min:2,max:60,step:1},{key:"width",label:"Width",input:"number",min:21},{key:"height",label:"Height",input:"number",min:21},{key:"constructorColor",label:"Bar color",input:"color"}],
  referenceIds:e=>[`${e.id}.axis`,`${e.id}.bars`,`${e.id}.min`,`${e.id}.max`,`${e.id}.count`,...Array.from({length:e.bins},(_v,i)=>`${e.id}.bar${i}`)],storyTargets(e){return this.referenceIds!(e).map((id):StoryTargetSpec=>({id,label:id,kind:id.includes(".bar")?"rect":id.endsWith(".count")||id.endsWith(".min")||id.endsWith(".max")?"text":"line"}));},applyReferenceModifier:applyChild,
});
export function processChildStyle(entity:LiveHistogramEntity,ref:string):VirtualChildStyle{return entity.childStyles[ref]??{};}
