import { argName, argString, escapeString } from "../args.js";
import { registerEntity, type Box, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import { CANVAS_SIZES, type RaceChartEntity, type RaceSeriesSpec, type SceneDoc, type VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

export interface RaceRow { label:string; icon:string|null; values:number[] }
export function racePeriods(entity:RaceChartEntity):string[]{return entity.periods.split(/[\s,]+/u).filter(Boolean);}
function parseBlock(block:string,periods:number):RaceRow[]{const lines=block.split(/[;\n]+/u).map(v=>v.trim()).filter(Boolean),comma=lines.some(v=>v.includes(",")),tab=lines.some(v=>v.includes("\t"));return lines.flatMap(line=>{const cells=(comma?line.split(","):tab?line.split("\t"):line.split(/\s+/u)).map(v=>v.trim()).filter(Boolean);if(cells.length<2)return[];const numeric=Number.isFinite(Number(cells[1])),icon=numeric?null:cells[1],start=numeric?1:2,values=cells.slice(start).map(Number);return values.length===periods&&values.every(Number.isFinite)?[{label:cells[0],icon,values}]:[];});}
export function raceRows(entity:RaceChartEntity):RaceRow[]{const n=racePeriods(entity).length;return[...entity.dataBlocks.flatMap(block=>parseBlock(block,n)),...entity.series.flatMap(series=>{const values=series.values.split(/[\s,]+/u).filter(Boolean).map(Number);return values.length===n&&values.every(Number.isFinite)?[{label:series.label,icon:series.icon,values}]:[];})];}
export function raceBox(doc?:SceneDoc):Box{const size=doc?.size??(doc?CANVAS_SIZES[doc.format]:CANVAS_SIZES["16:9"]);return{x:size.width*.055,y:size.height*.055,width:size.width*.89,height:size.height*.88};}
function childStyle(e:RaceChartEntity,ref:string):VirtualChildStyle{return e.childStyles[ref]??(e.childStyles[ref]={});}
function applyChild(e:RaceChartEntity,ref:string,stmt:CallStatement):boolean{const style=childStyle(e,ref);if(stmt.name==="color"){const v=argName(stmt.args,1);if(!v)return false;style.color=v;return true;}return false;}
function childLines(styles:Record<string,VirtualChildStyle>):string[]{return Object.entries(styles).flatMap(([ref,s])=>s.color?[`color(${ref}, ${s.color});`]:[]);}
function base(id:string):RaceChartEntity{return{...baseEntity(id,"cyan"),nativePaint:true,kind:"racechart",layout:"bar",periods:"2000 2010 2020",title:null,dataBlocks:[],series:[],companion:null,panel:false,childStyles:{}};}
function series(stmt:CallStatement):RaceSeriesSpec|null{const label=argString(stmt.args,1);if(label===null||stmt.args.length<3||stmt.args.length>4)return null;const icon=stmt.args.length===4?argString(stmt.args,2):null,values=argString(stmt.args,stmt.args.length===4?3:2);return values===null||(stmt.args.length===4&&icon===null)?null:{label,icon,values};}

registerEntity<RaceChartEntity>({kind:"racechart",ctor:"racechart",group:"Charts",label:"Race chart",icon:"▰↕",order:109,fidelity:"semantic",hint:"Responsive data race; Canvas shows one authored period while Preview owns ranking playback",movable:false,
  create(id){return base(id);},parseArgs(stmt){const id=argName(stmt.args,0),layout=argString(stmt.args,1) as RaceChartEntity["layout"]|null,periods=argString(stmt.args,2),title=argString(stmt.args,3);if(!id||!layout||!["bar","column","line"].includes(layout)||periods===null||stmt.args.length<3||stmt.args.length>4||(stmt.args.length===4&&title===null))return null;return{...base(id),layout,periods,title};},
  ctorLine:e=>`racechart(${e.id}, "${e.layout}", "${escapeString(e.periods)}"${e.title===null?"":`, "${escapeString(e.title)}"`});`,
  extraLines(e){return[...e.dataBlocks.map(block=>`racedata(${e.id}, "${escapeString(block)}");`),...e.series.map(row=>`raceseries(${e.id}, "${escapeString(row.label)}", ${row.icon===null?"":`"${escapeString(row.icon)}", `}"${escapeString(row.values)}");`),...(e.companion?[`raceline(${e.id}, "${escapeString(e.companion.label)}"${e.companion.values===null?"":`, "${escapeString(e.companion.values)}"`});`]:[]),...(e.panel?[`racepanel(${e.id});`]:[]),...childLines(e.childStyles)];},
  modifiers:{racedata(e,stmt){const block=argString(stmt.args,1);if(block===null||stmt.args.length!==2)return false;e.dataBlocks.push(block);return true;},raceseries(e,stmt){const row=series(stmt);if(!row)return false;e.series.push(row);return true;},raceline(e,stmt){if(stmt.args.length>3)return false;const label=argString(stmt.args,1)??"Total",values=argString(stmt.args,2);if(stmt.args.length>2&&values===null)return false;e.companion={label,values};return true;},racepanel(e,stmt){if(stmt.args.length!==1)return false;e.panel=true;return true;}},
  anchor(e,ctx){const b=raceBox(ctx?.doc);return{x:b.x+b.width/2,y:b.y+b.height/2};},translate(){},bounds(_e,ctx){return raceBox(ctx?.doc);},handles:()=>[],dragHandle(){},fields:[{key:"layout",label:"Layout",input:"select",options:["bar","column","line"]},{key:"periods",label:"Period labels",input:"text"},{key:"title",label:"Title",input:"text",nullable:true}],
  referenceIds(e){const count=raceRows(e).length;return[`${e.id}.period`,`${e.id}.axis`,`${e.id}.yaxis`,`${e.id}.title`,`${e.id}.total`,`${e.id}.bars`,`${e.id}.labels`,`${e.id}.values`,`${e.id}.icons`,`${e.id}.lines`,`${e.id}.dots`,`${e.id}.panel`,`${e.id}.cline`,`${e.id}.cdot`,`${e.id}.cval`,`${e.id}.pcursor`,...Array.from({length:count},(_v,i)=>[`${e.id}.bar${i}`,`${e.id}.lbl${i}`,`${e.id}.val${i}`,`${e.id}.icon${i}`,`${e.id}.dot${i}`,`${e.id}.pline${i}`]).flat()];},
  storyTargets(e){return this.referenceIds!(e).map((id):StoryTargetSpec=>({id,label:id,kind:id.includes(".lbl")||id.includes(".val")||id.endsWith(".period")?"text":id.includes(".bar")?"rect":"line"}));},applyReferenceModifier:applyChild,
});
export function raceChildStyle(entity:RaceChartEntity,ref:string):VirtualChildStyle{return entity.childStyles[ref]??{};}
