// Native Stats-kit compositions. Small deterministic charts are reproduced on
// Canvas; high-count seeded experiments retain exact inputs but use bounded
// semantic samples so authoring remains responsive.

import { argName, argNumber, argPoint, argString, escapeString, num, pt } from "../args.js";
import { registerEntity, type Box, type FieldSpec, type StoryTargetSpec } from "../registry.js";
import type { CallStatement } from "../script.js";
import type { Point, StatsEntity, StatsKind, VirtualChildStyle } from "../types.js";
import { baseEntity } from "./base.js";

export const STATS_CANVAS_POINT_CAP = 600;
export const STATS_CANVAS_TRIAL_CAP = 1200;

export type StatsPrimitive =
  | { id: string; kind: "line"; from: Point; to: Point; color: string; width: number; opacity: number; tags: string[] }
  | { id: string; kind: "rect"; x: number; y: number; width: number; height: number; color: string; opacity: number; outline?: boolean; tags: string[] }
  | { id: string; kind: "circle"; x: number; y: number; radius: number; color: string; opacity: number; fill?: boolean; tags: string[] }
  | { id: string; kind: "polyline" | "polygon"; points: Point[]; color: string; width: number; opacity: number; tags: string[] }
  | { id: string; kind: "text"; x: number; y: number; text: string; size: number; color: string; opacity: number; tags: string[] };

export interface StatsGeometry { primitives: StatsPrimitive[]; issue: string | null; semantic: boolean; note: string | null }

const move = (entity: StatsEntity, dx: number, dy: number) => { entity.x += dx; entity.y += dy; };
const vals = (source: string) => source.split(/[\s,]+/u).filter(Boolean).flatMap((token) => { const value = Number(token); return Number.isFinite(value) ? [value] : []; });
const points = (source: string) => { const values = vals(source); return Array.from({ length: Math.floor(values.length / 2) }, (_unused, index) => ({ x: values[index * 2], y: values[index * 2 + 1] })); };
const mean = (data: number[]) => data.reduce((sum, value) => sum + value, 0) / Math.max(1, data.length);
const median = (data: number[]) => { const sorted = [...data].sort((a, b) => a - b), n = sorted.length; return n ? n % 2 ? sorted[Math.floor(n / 2)] : (sorted[n / 2 - 1] + sorted[n / 2]) / 2 : 0; };
const fmt = (value: number) => Math.abs(value - Math.round(value)) < 1e-4 ? String(Math.round(value)) : value.toFixed(1);
const clamp = (value: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, value));
const color = (entity: StatsEntity, fallback = "cyan") => entity.constructorPaint && entity.constructorPaint !== "rainbow" ? entity.constructorPaint : fallback;
const rainbow = (index: number, count: number) => `hsl(${360 * index / Math.max(1, count)} 100% 60%)`;
const tags = (entity: StatsEntity, ...rest: string[]) => [entity.id, ...rest];
const line = (entity: StatsEntity, id: string, from: Point, to: Point, paint = "dim", width = 2, opacity = .8, extra: string[] = []): StatsPrimitive => ({ id: `${entity.id}.${id}`, kind: "line", from, to, color: paint, width, opacity, tags: tags(entity, ...extra) });
const text = (entity: StatsEntity, id: string, value: string, x: number, y: number, paint = "dim", size = 18): StatsPrimitive => ({ id: `${entity.id}.${id}`, kind: "text", x, y, text: value, size, color: paint, opacity: 1, tags: tags(entity) });
const circle = (entity: StatsEntity, id: string, x: number, y: number, radius: number, paint: string, extra: string[] = [], opacity = 1, fill = true): StatsPrimitive => ({ id: `${entity.id}.${id}`, kind: "circle", x, y, radius, color: paint, opacity, fill, tags: tags(entity, ...extra) });
const rect = (entity: StatsEntity, id: string, x: number, y: number, width: number, height: number, paint: string, extra: string[] = [], opacity = .85, outline = true): StatsPrimitive => ({ id: `${entity.id}.${id}`, kind: "rect", x, y, width, height, color: paint, opacity, outline, tags: tags(entity, ...extra) });
const path = (entity: StatsEntity, id: string, pts: Point[], paint: string, kind: "polyline" | "polygon" = "polyline", width = 3, opacity = 1, extra: string[] = []): StatsPrimitive => ({ id: `${entity.id}.${id}`, kind, points: pts, color: paint, width, opacity, tags: tags(entity, ...extra) });

function bins(data: number[], count: number, fixed?: [number, number]): { lo: number; hi: number; counts: number[] } {
  const lo = fixed?.[0] ?? Math.min(...data), hi = fixed?.[1] ?? Math.max(...data), span = Math.max(1e-6, hi - lo), counts = Array.from({ length: count }, () => 0);
  for (const value of data) counts[clamp(Math.floor((value - lo) / span * count), 0, count - 1)]++;
  return { lo, hi, counts };
}

function histogramPrimitives(entity: StatsEntity, data: number[], count: number, width: number, height: number, skew = false): StatsPrimitive[] {
  const result: StatsPrimitive[] = [], binned = bins(data, count), span = Math.max(1e-6, binned.hi - binned.lo), max = Math.max(1, ...binned.counts), x0 = entity.x - width / 2, baseline = entity.y + height / 2, barWidth = width / count, paint = color(entity);
  result.push(line(entity, "axis", { x: x0, y: baseline }, { x: x0 + width, y: baseline }));
  binned.counts.forEach((value, index) => { const h = value / max * height, barPaint = entity.constructorPaint === "rainbow" ? rainbow(index, count) : paint; result.push(rect(entity, `bar${index}`, x0 + (index + .05) * barWidth, baseline - h, barWidth * .9, h, barPaint, [`${entity.id}.bars`], .82)); });
  const average = mean(data), sx = (value: number) => x0 + (value - binned.lo) / span * width;
  result.push(line(entity, "meanline", { x: sx(average), y: baseline }, { x: sx(average), y: baseline - height - 10 }, "gold", 2, .9));
  if (skew) {
    const middle = median(data), variance = mean(data.map((value) => (value - average) ** 2)), third = mean(data.map((value) => (value - average) ** 3)), coefficient = variance < 1e-9 ? 0 : third / variance ** 1.5;
    result.push(line(entity, "medianline", { x: sx(middle), y: baseline }, { x: sx(middle), y: baseline - height - 8 }, "magenta", 2, .9));
    result.push(text(entity, "meanlbl", "mean", sx(average), baseline - height - 42, "gold", 16), text(entity, "medianlbl", "median", sx(middle), baseline - height - 22, "magenta", 16));
    const reading = Math.abs(coefficient) < .15 ? "≈ symmetric" : coefficient > 0 ? "right-skewed" : "left-skewed";
    result.push(text(entity, "skewlbl", `skew = ${coefficient >= 0 ? "+" : ""}${coefficient.toFixed(2)}   (${reading})`, entity.x, baseline + 32, paint, 22));
  } else {
    result.push(text(entity, "mean", "mean", sx(average), baseline - height - 28, "gold"), text(entity, "min", fmt(binned.lo), x0, baseline + 22), text(entity, "max", fmt(binned.hi), x0 + width, baseline + 22));
  }
  return result;
}

function regression(data: Point[]): { slope: number; intercept: number; r: number } | null {
  const n = data.length, sx = data.reduce((v, p) => v + p.x, 0), sy = data.reduce((v, p) => v + p.y, 0), sxx = data.reduce((v, p) => v + p.x * p.x, 0), syy = data.reduce((v, p) => v + p.y * p.y, 0), sxy = data.reduce((v, p) => v + p.x * p.y, 0), dx = n * sxx - sx * sx, dy = n * syy - sy * sy;
  if (Math.abs(dx) < 1e-9 || Math.abs(dy) < 1e-9) return null;
  return { slope: (n * sxy - sx * sy) / dx, intercept: (sy - ((n * sxy - sx * sy) / dx) * sx) / n, r: (n * sxy - sx * sy) / Math.sqrt(dx * dy) };
}

function gaussianCurve(entity: StatsEntity, mu: number, sigma: number, unit: number, paint: string): StatsPrimitive[] {
  const h = 220, base = entity.y + h / 2, px = (z: number) => entity.x + z * unit, py = (z: number) => base - Math.exp(-.5 * z * z) * h, out: StatsPrimitive[] = [line(entity, "axis", { x: px(-3.6), y: base }, { x: px(3.6), y: base })];
  for (const k of [3, 2, 1]) { const pts: Point[] = [{ x: px(-k), y: base }]; for (let i = 0; i <= 80; i++) { const z = -k + 2 * k * i / 80; pts.push({ x: px(z), y: py(z) }); } pts.push({ x: px(k), y: base }); out.push(path(entity, `band${k}`, pts, paint, "polygon", 0, .16, [`${entity.id}.bands`])); out.push(text(entity, `p${k}`, k === 1 ? "68%" : k === 2 ? "95%" : "99.7%", px(k === 1 ? 0 : k - .5), k === 1 ? base - h * .45 : base - 34, paint, 20)); }
  const curve: Point[] = []; for (let i = 0; i <= 140; i++) { const z = -3.6 + 7.2 * i / 140; curve.push({ x: px(z), y: py(z) }); }
  out.push(path(entity, "curve", curve, paint), line(entity, "mean", { x: px(0), y: base }, { x: px(0), y: py(0) }, "gold", 2, .9));
  for (let k = -3; k <= 3; k++) out.push(text(entity, `t${k}`, fmt(mu + k * sigma), px(k), base + 22, k === 0 ? "gold" : "dim", 17));
  return out;
}

function betaCurve(entity: StatsEntity, name: string, aa: number, bb: number, width: number, height: number, paint: string): StatsPrimitive {
  const x0 = entity.x - width / 2, base = entity.y + height / 2, density = Array.from({ length: 161 }, (_unused, i) => { const p = i / 160; return p ** (aa - 1) * (1 - p) ** (bb - 1); }), peak = Math.max(1e-9, ...density);
  return path(entity, name, density.map((d, i) => ({ x: x0 + i / 160 * width, y: base - d / peak * height })), paint);
}

function lcg(seed: number): () => number { let state = BigInt.asUintN(64, BigInt(Math.trunc(seed)) + 1n); return () => { state = BigInt.asUintN(64, state * 6364136223846793005n + 1442695040888963407n); return Number(state >> 40n) / 16777216; }; }
function factorial(value: number): number { let out = 1; for (let k = 2; k <= value; k++) out *= k; return out; }

export function statsGeometry(entity: StatsEntity): StatsGeometry {
  const out: StatsPrimitive[] = [], data = vals(entity.data), pts = points(entity.data), fail = (issue: string): StatsGeometry => ({ primitives: [], issue, semantic: false, note: null });
  switch (entity.kind) {
    case "histogram": { if (data.length < 2) return fail("Histogram needs at least two numbers."); const count = clamp(Math.round(entity.p1 ?? Math.sqrt(data.length)), 2, 60), width = entity.p2 ?? 460, height = entity.p3 ?? 240; out.push(...histogramPrimitives(entity, data, count, width, height)); break; }
    case "skew": { if (data.length < 3) return fail("Skew needs at least three numbers."); const count = clamp(Math.round(entity.p1 ?? Math.sqrt(data.length)), 2, 60); out.push(...histogramPrimitives(entity, data, count, entity.p2 ?? 520, entity.p3 ?? 240, true)); break; }
    case "correlation":
    case "covariance": { if (pts.length < 3) return fail(`${entity.kind} needs at least three point pairs.`); const unit = entity.p1 ?? 40, mx = mean(pts.map((p) => p.x)), my = mean(pts.map((p) => p.y)), sc = (p: Point) => ({ x: entity.x + (p.x - mx) * unit, y: entity.y - (p.y - my) * unit }), accent = color(entity, entity.kind === "covariance" ? "gold" : "cyan");
      if (entity.kind === "covariance") { const ext = Math.max(...pts.map((p) => Math.max(Math.abs(p.x - mx), Math.abs(p.y - my)))) + 1; pts.forEach((p, i) => { const a = sc({ x: mx, y: my }), b = sc(p), positive = (p.x - mx) * (p.y - my) >= 0; out.push(rect(entity, `rect${i}`, Math.min(a.x, b.x), Math.min(a.y, b.y), Math.abs(a.x - b.x), Math.abs(a.y - b.y), positive ? "cyan" : "magenta", [`${entity.id}.rects`], .13, false)); }); out.push(line(entity, "crossv", sc({ x: mx, y: my - ext }), sc({ x: mx, y: my + ext }), "dim", 2, .8, [`${entity.id}.cross`]), line(entity, "crossh", sc({ x: mx - ext, y: my }), sc({ x: mx + ext, y: my }), "dim", 2, .8, [`${entity.id}.cross`])); const cov = mean(pts.map((p) => (p.x - mx) * (p.y - my))); out.push(text(entity, "cov", `cov = ${cov >= 0 ? "+" : ""}${cov.toFixed(2)}   (${cov >= 0 ? "positive" : "negative"} relationship)`, entity.x, entity.y + ext * unit + 30, cov >= 0 ? "cyan" : "magenta", 22)); }
      else { const fit = regression(pts); if (!fit) return fail("Correlation requires spread in both x and y."); const lo = Math.min(...pts.map((p) => p.x)), hi = Math.max(...pts.map((p) => p.x)), pad = (hi - lo) * .1 + .5; out.push(line(entity, "line", sc({ x: lo - pad, y: fit.slope * (lo - pad) + fit.intercept }), sc({ x: hi + pad, y: fit.slope * (hi + pad) + fit.intercept }), "gold", 3, 1)); const strength = Math.abs(fit.r) > .7 ? "strong" : Math.abs(fit.r) > .4 ? "moderate" : "weak"; out.push(text(entity, "r", `r = ${fit.r >= 0 ? "+" : ""}${fit.r.toFixed(2)}   (${strength} ${fit.r >= 0 ? "positive" : "negative"})`, entity.x, entity.y + 200, accent, 22)); }
      pts.forEach((p, i) => out.push(circle(entity, `p${i}`, sc(p).x, sc(p).y, 7, accent, [`${entity.id}.points`]))); break; }
    case "bayes": {
      const heads = Math.max(0, Math.trunc(entity.p1 ?? 8)), tails = Math.max(0, Math.trunc(entity.p2 ?? 4)), width = entity.p3 ?? 620, height = entity.p4 ?? 260;
      const x0 = entity.x - width / 2, base = entity.y + height / 2, posterior = (heads + 2) / (heads + tails + 4);
      out.push(line(entity, "axis", { x: x0, y: base }, { x: x0 + width, y: base }));
      for (const [value, label] of [[0, "0"], [.5, "0.5"], [1, "1"]] as const) out.push(text(entity, `t${Math.round(value * 10)}`, label, x0 + value * width, base + 22, "dim", 16));
      out.push(betaCurve(entity, "prior", 2, 2, width, height, "gold"), betaCurve(entity, "likelihood", heads + 1, tails + 1, width, height, "magenta"), betaCurve(entity, "posterior", heads + 2, tails + 2, width, height, "cyan"));
      out.push(line(entity, "mean", { x: x0 + posterior * width, y: base }, { x: x0 + posterior * width, y: base - height }, "cyan", 2, .7));
      out.push(text(entity, "priorlbl", "prior", entity.x, base - height * .28, "gold"), text(entity, "postlbl", `posterior  (p ~ ${posterior.toFixed(2)})`, x0 + posterior * width, base - height - 16, "cyan"), text(entity, "datalbl", `${heads} heads, ${tails} tails`, entity.x, base + 50, "magenta", 20));
      break;
    }
    case "hypothesis": {
      const z = Math.abs(entity.p1 ?? 1.96), alpha = entity.p2 ?? .05, unit = entity.p3 ?? 80, h = 220, base = entity.y + h / 2;
      const bx = (value: number) => entity.x + value * unit, by = (value: number) => base - Math.exp(-.5 * value * value) * h;
      out.push(line(entity, "axis", { x: bx(-3.8), y: base }, { x: bx(3.8), y: base }));
      for (const [name, from, to] of [["lo", -3.8, -Math.min(z, 3.8)], ["hi", Math.min(z, 3.8), 3.8]] as const) {
        if (to <= from) continue;
        const tail: Point[] = [{ x: bx(from), y: base }];
        for (let i = 0; i <= 40; i++) { const value = from + (to - from) * i / 40; tail.push({ x: bx(value), y: by(value) }); }
        tail.push({ x: bx(to), y: base });
        out.push(path(entity, `tail${name}`, tail, "magenta", "polygon", 0, .5, [`${entity.id}.tails`]));
      }
      const curve: Point[] = [];
      for (let i = 0; i <= 130; i++) { const value = -3.8 + 7.6 * i / 130; curve.push({ x: bx(value), y: by(value) }); }
      out.push(path(entity, "curve", curve, "cyan"));
      out.push(line(entity, "zlinehi", { x: bx(z), y: base }, { x: bx(z), y: by(z) }, "gold", 2.5, 1, [`${entity.id}.zline`]), line(entity, "zlinelo", { x: bx(-z), y: base }, { x: bx(-z), y: by(-z) }, "gold", 2.5, 1, [`${entity.id}.zline`]));
      const p = Math.min(1, erfc(z / Math.SQRT2));
      out.push(text(entity, "zlbl", `z = ${z.toFixed(2)}`, bx(z), by(z) - 16, "gold"), text(entity, "p", `p = ${p.toFixed(3)}`, entity.x, base + 34, "magenta", 22), text(entity, "verdict", p < alpha ? `p < ${alpha} — reject the null hypothesis` : `p >= ${alpha} — fail to reject`, entity.x, base + 62, "fg", 20));
      break;
    }
    case "bellcurve": { const sigma = entity.p2 ?? 1; if (sigma <= 0) return fail("Bell curve sigma must be positive."); out.push(...gaussianCurve(entity, entity.p1 ?? 0, sigma, entity.p3 ?? 80, color(entity))); break; }
    case "summary": {
      if (data.length < 2) return fail("Summary needs at least two numbers.");
      const width = entity.p1 ?? 640, accent = color(entity), average = mean(data), middle = median(data);
      const variance = mean(data.map((value) => (value - average) ** 2)), std = Math.sqrt(variance), sorted = [...data].sort((a, b) => a - b);
      const lo = sorted[0], hi = sorted.at(-1)!, pad = (hi - lo) * .08 + .5, y = entity.y + 30;
      const sx = (value: number) => entity.x - width / 2 + (value - (lo - pad)) / (hi - lo + 2 * pad) * width;
      out.push(rect(entity, "band", sx(average - std), y - 76, Math.abs(sx(average + std) - sx(average - std)), 84, accent, [], .12, false));
      out.push(line(entity, "line", { x: sx(lo - pad), y }, { x: sx(hi + pad), y }));
      data.forEach((value, index) => out.push(circle(entity, `dot${index}`, sx(value), y, 5, "fg", [`${entity.id}.dots`], .45)));
      const markers: Array<[string, number, number, string]> = [["mean", average, 92, "gold"], ["median", middle, 66, "magenta"]];
      for (const [name, value, height, paint] of markers) {
        out.push(line(entity, `${name}mark`, { x: sx(value), y }, { x: sx(value), y: y - height }, paint, 2.5, .95));
        out.push(text(entity, `${name}lbl`, `${name} ${fmt(value)}`, sx(value), y - height - 14, paint));
      }
      const dataMode = modeOf(sorted);
      if (dataMode !== null) {
        out.push(line(entity, "modemark", { x: sx(dataMode), y }, { x: sx(dataMode), y: y - 40 }, "lime", 2.5, .95));
        out.push(text(entity, "modelbl", `mode ${fmt(dataMode)}`, sx(dataMode), y - 54, "lime"));
      }
      out.push(text(entity, "min", fmt(lo), sx(lo), y + 22, "dim", 16), text(entity, "max", fmt(hi), sx(hi), y + 22, "dim", 16));
      out.push(text(entity, "readout", `n = ${data.length}     range ${fmt(hi - lo)}     variance ${variance.toFixed(1)}     std ${std.toFixed(1)}`, entity.x, y + 60, accent, 20));
      break;
    }
    case "boxplot": { if (data.length < 4) return fail("Box plot needs at least four numbers."); const sorted = [...data].sort((a, b) => a - b), n = sorted.length, middle = median(sorted), q1 = median(sorted.slice(0, Math.floor(n / 2))), q3 = median(sorted.slice(Math.ceil(n / 2))), iqr = q3 - q1, flo = q1 - 1.5 * iqr, fhi = q3 + 1.5 * iqr, wlo = Math.min(...sorted.filter((v) => v >= flo)), whi = Math.max(...sorted.filter((v) => v <= fhi)), lo = Math.min(...sorted), hi = Math.max(...sorted), width = entity.p1 ?? 640, pad = (hi - lo) * .08 + .5, sx = (v: number) => entity.x - width / 2 + (v - (lo - pad)) / (hi - lo + 2 * pad) * width, y = entity.y, accent = color(entity); out.push(line(entity, "whiskerlo", { x: sx(wlo), y }, { x: sx(q1), y }), line(entity, "whiskerhi", { x: sx(q3), y }, { x: sx(whi), y }), line(entity, "caplo", { x: sx(wlo), y: y - 20 }, { x: sx(wlo), y: y + 20 }), line(entity, "caphi", { x: sx(whi), y: y - 20 }, { x: sx(whi), y: y + 20 }), rect(entity, "box", sx(q1), y - 44, Math.max(1, sx(q3) - sx(q1)), 88, accent, [], .2), line(entity, "med", { x: sx(middle), y: y - 44 }, { x: sx(middle), y: y + 44 }, "gold", 3, 1), text(entity, "iqr", `IQR = ${fmt(iqr)}`, (sx(q1) + sx(q3)) / 2, y - 66, accent, 20)); data.forEach((v, i) => { if (v < flo || v > fhi) out.push(circle(entity, `out${i}`, sx(v), y, 6, "magenta", [`${entity.id}.outliers`])); }); [["min", wlo, "dim"], ["med", middle, "gold"], ["max", whi, "dim"], ["q1", q1, accent], ["q3", q3, accent]].forEach(([name, value, paint], i) => out.push(text(entity, `l${name}`, fmt(value as number), sx(value as number), y + (i < 3 ? 68 : 90), paint as string, 17))); break; }
    case "distribution": { const mode = entity.mode, a = entity.p1 ?? 1, b = entity.p2 ?? 0, width = 540, height = 240, x0 = entity.x - width / 2, base = entity.y + height / 2, accent = color(entity), drawDensity = (lo: number, hi: number, fn: (v: number) => number) => { const densities = Array.from({ length: 161 }, (_unused, i) => fn(lo + (hi - lo) * i / 160)), peak = Math.max(1e-9, ...densities); out.push(path(entity, "curve", densities.map((d, i) => ({ x: x0 + i / 160 * width, y: base - d / peak * height })), accent)); }, drawBars = (probs: number[]) => { const max = Math.max(1e-12, ...probs), bw = width / probs.length; probs.forEach((p, i) => out.push(rect(entity, `bar${i}`, x0 + (i + .075) * bw, base - p / max * height, bw * .85, p / max * height, entity.constructorPaint === "rainbow" ? rainbow(i, probs.length) : accent, [`${entity.id}.bars`], .85))); }; let label = ""; out.push(line(entity, "axis", { x: x0, y: base }, { x: x0 + width, y: base })); if (mode === "uniform") { const hi = Math.max(b, a + 1e-3), pad = (hi - a) * .25; drawDensity(a - pad, hi + pad, (v) => v >= a && v <= hi ? 1 : 0); label = `uniform [${fmt(a)}, ${fmt(hi)}]`; } else if (mode === "exponential") { const rate = Math.max(.001, a); drawDensity(0, 5 / rate, (v) => rate * Math.exp(-rate * v)); label = `exponential  (rate ${fmt(rate)})`; } else if (mode === "maxwell") { const scale = Math.max(.001, a); drawDensity(0, 4 * scale, (v) => Math.sqrt(2 / Math.PI) * v * v / scale ** 3 * Math.exp(-v * v / (2 * scale * scale))); label = `Maxwell speed  (scale ${fmt(scale)})`; } else if (mode === "binomial") { const n = clamp(Math.round(a), 1, 20), p = clamp(b, 0, 1); drawBars(Array.from({ length: n + 1 }, (_unused, k) => factorial(n) / (factorial(k) * factorial(n - k)) * p ** k * (1 - p) ** (n - k))); label = `binomial  (n = ${n}, p = ${fmt(p)})`; } else if (mode === "poisson") { const lambda = Math.max(.1, a), max = Math.min(30, Math.floor(lambda * 2.5) + 6); drawBars(Array.from({ length: max + 1 }, (_unused, k) => lambda ** k * Math.exp(-lambda) / factorial(k))); label = `poisson  (mean ${fmt(lambda)})`; } else return fail(`Unknown distribution “${mode}”.`); out.push(text(entity, "name", label, entity.x, base + 34, accent, 22)); break; }
    case "confidence": { const estimate = entity.p1 ?? 50, sd = entity.p2 ?? 10, n = Math.max(1, entity.p3 ?? 100), level = entity.p4 ?? 95, width = entity.p5 ?? 560, z = level >= 99 ? 2.576 : level >= 95 ? 1.96 : 1.645, margin = z * sd / Math.sqrt(n), span = Math.max(.001, margin * 3), sx = (v: number) => entity.x + (v - estimate) / span * width / 2, y = entity.y; out.push(line(entity, "line", { x: sx(estimate - span), y }, { x: sx(estimate + span), y }, "dim", 2, .7), line(entity, "bar", { x: sx(estimate - margin), y }, { x: sx(estimate + margin), y }, "cyan", 4, 1), line(entity, "caplo", { x: sx(estimate - margin), y: y - 18 }, { x: sx(estimate - margin), y: y + 18 }, "cyan", 3, 1), line(entity, "caphi", { x: sx(estimate + margin), y: y - 18 }, { x: sx(estimate + margin), y: y + 18 }, "cyan", 3, 1), circle(entity, "estimate", sx(estimate), y, 8, "gold"), text(entity, "blo", fmt(estimate - margin), sx(estimate - margin), y + 40, "dim", 17), text(entity, "bhi", fmt(estimate + margin), sx(estimate + margin), y + 40, "dim", 17), text(entity, "ci", `${fmt(level)}% CI:  ${fmt(estimate)} ± ${fmt(margin)}`, entity.x, y - 44, "gold", 22)); break; }
    case "montecarlo": { const authored = clamp(Math.round(entity.p1 ?? 500), 20, 4000), shown = Math.min(authored, STATS_CANVAS_POINT_CAP), seed = entity.p2 ?? 12345, size = entity.p3 ?? 230, random = lcg(seed); let inside = 0; out.push(rect(entity, "square", entity.x - size, entity.y - size, size * 2, size * 2, "dim", [], 1, true), circle(entity, "circle", entity.x, entity.y, size, "gold", [], 1, false)); for (let i = 0; i < shown; i++) { const x = random() * 2 - 1, y = random() * 2 - 1, hit = x * x + y * y <= 1; if (hit) inside++; out.push(circle(entity, `pt${i}`, entity.x + x * size, entity.y - y * size, 3.5, hit ? "cyan" : "magenta", [`${entity.id}.points`])); } out.push(text(entity, "pi", `π ≈ ${(4 * inside / shown).toFixed(3)}   (${authored} authored darts)`, entity.x, entity.y + size + 34, "gold", 22)); return { primitives: out, issue: null, semantic: authored > shown, note: authored > shown ? `Canvas samples ${shown} of ${authored} seeded darts; Preview renders all.` : null }; }
    case "randomwalk": { const authored = clamp(Math.round(entity.p1 ?? 200), 2, 3000), shown = Math.min(authored, STATS_CANVAS_TRIAL_CAP), random = lcg(entity.p2 ?? 12345), scale = entity.p3 ?? 14, walk: Point[] = [{ x: entity.x, y: entity.y }]; for (let i = 0; i < shown; i++) { const angle = random() * Math.PI * 2, last = walk.at(-1)!; walk.push({ x: last.x + scale * Math.cos(angle), y: last.y + scale * Math.sin(angle) }); } out.push(path(entity, "path", walk, "cyan", "polyline", 2, .9), circle(entity, "start", entity.x, entity.y, 7, "lime"), circle(entity, "end", walk.at(-1)!.x, walk.at(-1)!.y, 7, "gold")); return { primitives: out, issue: null, semantic: authored > shown, note: authored > shown ? `Canvas follows the first ${shown} of ${authored} seeded steps; Preview renders the full walk.` : null }; }
    case "lln": { const authored = clamp(Math.round(entity.p1 ?? 400), 10, 5000), shown = Math.min(authored, STATS_CANVAS_TRIAL_CAP), random = lcg(entity.p2 ?? 12345), width = entity.p3 ?? 680, height = entity.p4 ?? 300, x0 = entity.x - width / 2, base = entity.y + height / 2; let heads = 0; const curve: Point[] = []; for (let i = 1; i <= shown; i++) { if (random() < .5) heads++; curve.push({ x: x0 + i / shown * width, y: base - heads / i * height }); } out.push(line(entity, "axis", { x: x0, y: base }, { x: x0 + width, y: base }), line(entity, "ref", { x: x0, y: base - height / 2 }, { x: x0 + width, y: base - height / 2 }, "gold", 2, .85), path(entity, "curve", curve, "cyan", "polyline", 2.5), text(entity, "truelbl", "true probability = 0.5", x0 + width - 130, base - height / 2 - 18, "gold"), text(entity, "finallbl", `after ${authored} flips${authored > shown ? " · sampled on Canvas" : ""}`, entity.x, base + 34, "cyan", 20)); return { primitives: out, issue: null, semantic: authored > shown, note: authored > shown ? `Canvas samples ${shown} seeded flips; Preview evaluates all ${authored}.` : null }; }
    case "clt": { const sampleSize = clamp(Math.round(entity.p1 ?? 10), 1, 100), authored = clamp(Math.round(entity.p2 ?? 500), 10, 5000), shown = Math.min(authored, STATS_CANVAS_TRIAL_CAP), random = lcg(entity.p3 ?? 12345), width = entity.p4 ?? 560, height = entity.p5 ?? 260, means: number[] = []; for (let i = 0; i < shown; i++) { let total = 0; for (let j = 0; j < sampleSize; j++) total += 1 + Math.min(5, Math.floor(random() * 6)); means.push(total / sampleSize); } const binned = bins(means, 30, [1, 6]), max = Math.max(1, ...binned.counts), x0 = entity.x - width / 2, base = entity.y + height / 2, bw = width / 30, accent = color(entity); out.push(line(entity, "axis", { x: x0, y: base }, { x: x0 + width, y: base })); binned.counts.forEach((count, i) => { const h = count / max * height; out.push(rect(entity, `bar${i}`, x0 + (i + .05) * bw, base - h, bw * .9, h, entity.constructorPaint === "rainbow" ? rainbow(i, 30) : accent, [`${entity.id}.bars`], .85)); }); const sigma = Math.sqrt(35 / 12) / Math.sqrt(sampleSize), curve: Point[] = []; for (let i = 0; i <= 120; i++) { const value = 1 + 5 * i / 120, z = (value - 3.5) / sigma; curve.push({ x: x0 + i / 120 * width, y: base - Math.exp(-.5 * z * z) * height }); } out.push(path(entity, "curve", curve, "gold"), line(entity, "mean", { x: x0 + width / 2, y: base }, { x: x0 + width / 2, y: base - height - 10 }, "gold", 2, .9), text(entity, "info", `average of ${sampleSize} dice, ${authored} times`, entity.x, base - height - 30, "dim", 20)); return { primitives: out, issue: null, semantic: authored > shown, note: authored > shown ? `Canvas samples ${shown} experiments; Preview runs all ${authored}.` : null }; }
  }
  return { primitives: out, issue: null, semantic: false, note: null };
}

function erfc(value: number): number { const z = Math.abs(value), t = 1 / (1 + .5 * z), ans = t * Math.exp(-z * z - 1.26551223 + t * (1.00002368 + t * (.37409196 + t * (.09678418 + t * (-.18628806 + t * (.27886807 + t * (-1.13520398 + t * (1.48851587 + t * (-.82215223 + t * .17087277))))))))); return value >= 0 ? ans : 2 - ans; }
function modeOf(sorted: number[]): number | null { let best = 1, run = 1, value = sorted[0]; for (let i = 1; i < sorted.length; i++) { run = Math.abs(sorted[i] - sorted[i - 1]) < 1e-6 ? run + 1 : 1; if (run > best) { best = run; value = sorted[i]; } } return best > 1 ? value : null; }

function childStyle(entity: StatsEntity, ref: string): VirtualChildStyle { return entity.childStyles[ref] ?? (entity.childStyles[ref] = {}); }
function applyChild(entity: StatsEntity, ref: string, stmt: CallStatement): boolean { const style = childStyle(entity, ref); if (stmt.name === "color") { const value = argName(stmt.args, 1); if (!value) return false; style.color = value; return true; } if (stmt.name === "opacity") { const value = argNumber(stmt.args, 1); if (value === null) return false; style.opacity = value; return true; } if (stmt.name === "hidden") { style.reveal = argName(stmt.args, 1) === "center" ? "grow" : "fade"; return true; } if (stmt.name === "untraced") { style.untraced = true; return true; } return false; }
function childLines(styles: Record<string, VirtualChildStyle>): string[] { return Object.entries(styles).flatMap(([ref, style]) => [...(style.color ? [`color(${ref}, ${style.color});`] : []), ...(style.opacity !== undefined ? [`opacity(${ref}, ${num(style.opacity)});`] : []), ...(style.reveal ? [`hidden(${ref}${style.reveal === "grow" ? ", center" : ""});`] : []), ...(style.untraced ? [`untraced(${ref});`] : [])]); }
function statsRefs(entity: StatsEntity): string[] { const geometry = statsGeometry(entity), refs = new Set<string>(); geometry.primitives.forEach((primitive) => { refs.add(primitive.id); primitive.tags.forEach((tag) => { if (tag !== entity.id) refs.add(tag); }); }); return [...refs]; }
function primitiveBounds(primitive: StatsPrimitive): Box { if (primitive.kind === "line") return { x: Math.min(primitive.from.x, primitive.to.x), y: Math.min(primitive.from.y, primitive.to.y), width: Math.abs(primitive.to.x - primitive.from.x), height: Math.abs(primitive.to.y - primitive.from.y) }; if (primitive.kind === "rect") return { x: primitive.x, y: primitive.y, width: primitive.width, height: primitive.height }; if (primitive.kind === "circle") return { x: primitive.x - primitive.radius, y: primitive.y - primitive.radius, width: primitive.radius * 2, height: primitive.radius * 2 }; if (primitive.kind === "text") return { x: primitive.x - primitive.text.length * primitive.size * .31, y: primitive.y - primitive.size * .6, width: primitive.text.length * primitive.size * .62, height: primitive.size * 1.2 }; const xs = primitive.points.map((p) => p.x), ys = primitive.points.map((p) => p.y); return { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) }; }
function union(boxes: Box[]): Box { if (!boxes.length) return { x: 0, y: 0, width: 0, height: 0 }; const x = Math.min(...boxes.map((b) => b.x)), y = Math.min(...boxes.map((b) => b.y)), right = Math.max(...boxes.map((b) => b.x + b.width)), bottom = Math.max(...boxes.map((b) => b.y + b.height)); return { x, y, width: right - x, height: bottom - y }; }

function base(id: string, kind: StatsKind, x: number, y: number): StatsEntity { return { ...baseEntity(id, "cyan"), nativePaint: true, kind, spelling: kind, x, y, data: "", mode: "", p1: null, p2: null, p3: null, p4: null, p5: null, constructorPaint: null, childStyles: {} }; }
function paintArg(stmt: CallStatement, index: number): string | null | false { if (stmt.args.length <= index) return null; return argName(stmt.args, index) ?? false; }
function common(kind: StatsKind, ctor: string, label: string, icon: string, order: number, fidelity: "exact" | "semantic", fields: FieldSpec[], create: (entity: StatsEntity) => void, parse: (stmt: CallStatement, entity: StatsEntity) => boolean, serialize: (entity: StatsEntity) => string, aliases: string[] = []) {
  registerEntity<StatsEntity>({ kind, ctor, aliases, group: "Stats", label, icon, order, fidelity, hint: fidelity === "exact" ? "Native statistical composition with editable inputs and stable generated children" : "Bounded deterministic Canvas sample; native Preview renders the complete authored experiment", anchorArgIndex: 1,
    create(id, x, y) { const entity = base(id, kind, x, y); create(entity); return entity; }, parseArgs(stmt) { const id = argName(stmt.args, 0), at = argPoint(stmt.args, 1); if (!id || !at) return null; const entity = base(id, kind, at.x, at.y); entity.spelling = stmt.name as StatsEntity["spelling"]; return parse(stmt, entity) ? entity : null; }, ctorLine: serialize, extraLines: (entity) => childLines(entity.childStyles), modifiers: {}, referenceIds: statsRefs, storyTargets(entity) { return statsRefs(entity).map((id): StoryTargetSpec => ({ id, label: id, kind: id.includes("bar") || id.endsWith(".box") || id.includes("rect") || id.endsWith(".band") ? "rect" : id.includes("pt") || id.includes("dot") || id.endsWith(".estimate") ? "dot" : id.includes("lbl") || id.endsWith(".mean") || id.endsWith(".r") || id.endsWith(".cov") || id.endsWith(".pi") || id.endsWith(".ci") || id.endsWith(".name") || id.endsWith(".info") || id.endsWith(".readout") ? "text" : "line" })); }, applyReferenceModifier: applyChild, anchor: (entity) => ({ x: entity.x, y: entity.y }), translate: move, bounds(entity) { const boxes = statsGeometry(entity).primitives.map(primitiveBounds); const b = union(boxes); return boxes.length ? { x: b.x - 12, y: b.y - 12, width: b.width + 24, height: b.height + 24 } : { x: entity.x - 150, y: entity.y - 70, width: 300, height: 140 }; }, referenceBounds(entity, ref) { const primitives = statsGeometry(entity).primitives.filter((primitive) => primitive.id === ref || primitive.tags.includes(ref)); return primitives.length ? union(primitives.map(primitiveBounds)) : null; }, handles: () => [], dragHandle() {}, fields });
}

const dataset = (minimum: number): FieldSpec => ({ key: "data", label: "Dataset", input: "textarea", hint: `Whitespace/comma-separated numbers; at least ${minimum}.` });
const pointData: FieldSpec = { key: "data", label: "Point pairs", input: "textarea", hint: "x1 y1 x2 y2 …; at least three pairs." };
const nullableNumber = (key: string, label: string, min?: number, step = 1): FieldSpec => ({ key, label, input: "number", nullable: true, min, step });
const paintField: FieldSpec = { key: "constructorPaint", label: "Constructor colour", input: "color", nullable: true };
const rainbowField: FieldSpec = { key: "constructorPaint", label: "Bar colour", input: "text", nullable: true, hint: "Palette colour or rainbow." };

common("histogram", "histogram", "Histogram", "▥", 70, "exact", [dataset(2), nullableNumber("p1", "Bins", 2), nullableNumber("p2", "Width", 1), nullableNumber("p3", "Height", 1), rainbowField], (e) => { e.data = "2 3 3 4 5 5 5 6 7 8"; }, (s, e) => { const data = argString(s.args, 2), p1 = argNumber(s.args, 3), p2 = argNumber(s.args, 4), p3 = argNumber(s.args, 5), paint = paintArg(s, 6); if (data === null || s.args.length < 3 || s.args.length > 7 || (s.args.length > 3 && p1 === null) || (s.args.length > 4 && p2 === null) || (s.args.length > 5 && p3 === null) || paint === false) return false; Object.assign(e, { data, p1, p2, p3, constructorPaint: paint, color: paint && paint !== "rainbow" ? paint : "cyan" }); return true; }, (e) => `histogram(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.data)}"${e.p1 === null && e.p2 === null && e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p1 ?? clamp(Math.round(Math.sqrt(Math.max(2, vals(e.data).length))), 5, 20))}`}${e.p2 === null && e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p2 ?? 460)}`}${e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p3 ?? 240)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
common("covariance", "covariance", "Covariance", "▧·", 70.1, "exact", [pointData, { key: "p1", label: "Pixels per unit", input: "number", min: .1, step: 1 }, paintField], (e) => { e.p1 = 45; e.data = "1 1 2 2 3 2 4 5 5 4"; }, (s, e) => { const unit = argNumber(s.args, 2), data = argString(s.args, 3), paint = paintArg(s, 4); if (unit === null || data === null || s.args.length < 4 || s.args.length > 5 || paint === false) return false; Object.assign(e, { p1: unit, data, constructorPaint: paint, color: paint ?? "gold" }); return true; }, (e) => `covariance(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 45)}, "${escapeString(e.data)}"${e.constructorPaint ? `, ${e.constructorPaint}` : ""});`);
common("bayes", "bayes", "Bayesian update", "P|D", 70.2, "exact", [{ key: "p1", label: "Heads", input: "number", min: 0, step: 1 }, { key: "p2", label: "Tails", input: "number", min: 0, step: 1 }, nullableNumber("p3", "Width", 1), nullableNumber("p4", "Height", 1)], (e) => { e.p1 = 8; e.p2 = 4; }, (s, e) => { const p1 = argNumber(s.args, 2), p2 = argNumber(s.args, 3), p3 = argNumber(s.args, 4), p4 = argNumber(s.args, 5); if (p1 === null || p2 === null || s.args.length < 4 || s.args.length > 6 || (s.args.length > 4 && p3 === null) || (s.args.length > 5 && p4 === null)) return false; Object.assign(e, { p1, p2, p3, p4 }); return true; }, (e) => `bayes(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 0)}, ${num(e.p2 ?? 0)}${e.p3 === null && e.p4 === null ? "" : `, ${num(e.p3 ?? 620)}`}${e.p4 === null ? "" : `, ${num(e.p4)}`});`);
common("hypothesis", "hypothesis", "Hypothesis test", "H₀", 70.3, "exact", [{ key: "p1", label: "Observed |z|", input: "number", min: 0, step: .01 }, nullableNumber("p2", "Alpha", 0, .01), nullableNumber("p3", "Pixels per z", 1)], (e) => { e.p1 = 1.96; }, (s, e) => { const p1 = argNumber(s.args, 2), p2 = argNumber(s.args, 3), p3 = argNumber(s.args, 4); if (p1 === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && p2 === null) || (s.args.length > 4 && p3 === null)) return false; Object.assign(e, { p1, p2, p3 }); return true; }, (e) => `hypothesis(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 1.96)}${e.p2 === null && e.p3 === null ? "" : `, ${num(e.p2 ?? .05)}`}${e.p3 === null ? "" : `, ${num(e.p3)}`});`);
common("bellcurve", "bellcurve", "Normal bell curve", "μσ", 70.4, "exact", [{ key: "p1", label: "Mean μ", input: "number", step: .1 }, { key: "p2", label: "Std σ", input: "number", min: .001, step: .1 }, nullableNumber("p3", "Pixels per σ", 1), paintField], (e) => { e.p1 = 0; e.p2 = 1; }, (s, e) => { const p1 = argNumber(s.args, 2), p2 = argNumber(s.args, 3), p3 = argNumber(s.args, 4), paint = paintArg(s, 5); if (p1 === null || p2 === null || s.args.length < 4 || s.args.length > 6 || (s.args.length > 4 && p3 === null) || paint === false) return false; Object.assign(e, { p1, p2, p3, constructorPaint: paint, color: paint ?? "cyan" }); return true; }, (e) => `${e.spelling}(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 0)}, ${num(e.p2 ?? 1)}${e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p3 ?? 80)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`, ["gaussian"]);
common("summary", "summary", "Descriptive summary", "x̄", 70.5, "exact", [dataset(2), nullableNumber("p1", "Width", 1), paintField], (e) => { e.data = "2 3 3 4 5 5 5 6 8"; }, (s, e) => { const data = argString(s.args, 2), p1 = argNumber(s.args, 3), paint = paintArg(s, 4); if (data === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && p1 === null) || paint === false) return false; Object.assign(e, { data, p1, constructorPaint: paint, color: paint ?? "cyan" }); return true; }, (e) => `summary(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.data)}"${e.p1 === null && e.constructorPaint === null ? "" : `, ${num(e.p1 ?? 640)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
common("correlation", "correlation", "Correlation", "r", 70.6, "exact", [pointData, { key: "p1", label: "Pixels per unit", input: "number", min: .1, step: 1 }, paintField], (e) => { e.p1 = 45; e.data = "1 1 2 2 3 2 4 5 5 4"; }, (s, e) => { const unit = argNumber(s.args, 2), data = argString(s.args, 3), paint = paintArg(s, 4); if (unit === null || data === null || s.args.length < 4 || s.args.length > 5 || paint === false) return false; Object.assign(e, { p1: unit, data, constructorPaint: paint, color: paint ?? "cyan" }); return true; }, (e) => `correlation(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 45)}, "${escapeString(e.data)}"${e.constructorPaint ? `, ${e.constructorPaint}` : ""});`);
common("skew", "skew", "Skewness", "↤▥↦", 70.7, "exact", [dataset(3), nullableNumber("p1", "Bins", 2), nullableNumber("p2", "Width", 1), nullableNumber("p3", "Height", 1), rainbowField], (e) => { e.data = "1 2 2 3 3 3 4 7 10"; }, (s, e) => { const data = argString(s.args, 2), p1 = argNumber(s.args, 3), p2 = argNumber(s.args, 4), p3 = argNumber(s.args, 5), paint = paintArg(s, 6); if (data === null || s.args.length < 3 || s.args.length > 7 || (s.args.length > 3 && p1 === null) || (s.args.length > 4 && p2 === null) || (s.args.length > 5 && p3 === null) || paint === false) return false; Object.assign(e, { data, p1, p2, p3, constructorPaint: paint, color: paint && paint !== "rainbow" ? paint : "cyan" }); return true; }, (e) => `skew(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.data)}"${e.p1 === null && e.p2 === null && e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p1 ?? clamp(Math.round(Math.sqrt(Math.max(3, vals(e.data).length))), 5, 20))}`}${e.p2 === null && e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p2 ?? 520)}`}${e.p3 === null && e.constructorPaint === null ? "" : `, ${num(e.p3 ?? 240)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
common("boxplot", "boxplot", "Box plot", "⊢□⊣", 70.8, "exact", [dataset(4), nullableNumber("p1", "Width", 1), paintField], (e) => { e.data = "1 2 3 4 5 6 7 12"; }, (s, e) => { const data = argString(s.args, 2), p1 = argNumber(s.args, 3), paint = paintArg(s, 4); if (data === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && p1 === null) || paint === false) return false; Object.assign(e, { data, p1, constructorPaint: paint, color: paint ?? "cyan" }); return true; }, (e) => `boxplot(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.data)}"${e.p1 === null && e.constructorPaint === null ? "" : `, ${num(e.p1 ?? 640)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
common("distribution", "distribution", "Probability distribution", "𝑃", 70.9, "exact", [{ key: "mode", label: "Distribution", input: "select", options: ["uniform", "exponential", "maxwell", "binomial", "poisson"] }, { key: "p1", label: "Parameter a", input: "number", step: .1 }, nullableNumber("p2", "Parameter b", 0, .1), rainbowField], (e) => { e.mode = "binomial"; e.p1 = 10; e.p2 = .5; }, (s, e) => { const mode = argString(s.args, 2), p1 = argNumber(s.args, 3), p2 = argNumber(s.args, 4), paint = paintArg(s, 5); if (mode === null || p1 === null || s.args.length < 4 || s.args.length > 6 || (s.args.length > 4 && p2 === null) || paint === false) return false; Object.assign(e, { mode, p1, p2, constructorPaint: paint, color: paint && paint !== "rainbow" ? paint : "cyan" }); return true; }, (e) => `distribution(${e.id}, ${pt(e.x, e.y)}, "${escapeString(e.mode)}", ${num(e.p1 ?? 1)}${e.p2 === null && e.constructorPaint === null ? "" : `, ${num(e.p2 ?? 0)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
common("confidence", "confidence", "Confidence interval", "↔", 71, "exact", [{ key: "p1", label: "Sample mean", input: "number", step: .1 }, { key: "p2", label: "Standard deviation", input: "number", min: 0, step: .1 }, { key: "p3", label: "Sample size n", input: "number", min: 1, step: 1 }, nullableNumber("p4", "Confidence %", 0, .1), nullableNumber("p5", "Width", 1)], (e) => { e.p1 = 50; e.p2 = 10; e.p3 = 100; }, (s, e) => { const ps = [2, 3, 4, 5, 6].map((i) => argNumber(s.args, i)); if (ps[0] === null || ps[1] === null || ps[2] === null || s.args.length < 5 || s.args.length > 7 || (s.args.length > 5 && ps[3] === null) || (s.args.length > 6 && ps[4] === null)) return false; [e.p1, e.p2, e.p3, e.p4, e.p5] = ps; return true; }, (e) => `confidence(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 0)}, ${num(e.p2 ?? 1)}, ${num(e.p3 ?? 1)}${e.p4 === null && e.p5 === null ? "" : `, ${num(e.p4 ?? 95)}`}${e.p5 === null ? "" : `, ${num(e.p5)}`});`);
common("montecarlo", "montecarlo", "Monte Carlo π", "π·", 71.1, "semantic", [{ key: "p1", label: "Darts", input: "number", min: 20, max: 4000, step: 10 }, nullableNumber("p2", "Seed", 0), nullableNumber("p3", "Half-size", 1)], (e) => { e.p1 = 500; }, (s, e) => { const p1 = argNumber(s.args, 2), p2 = argNumber(s.args, 3), p3 = argNumber(s.args, 4); if (p1 === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && p2 === null) || (s.args.length > 4 && p3 === null)) return false; Object.assign(e, { p1, p2, p3 }); return true; }, (e) => `montecarlo(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 500)}${e.p2 === null && e.p3 === null ? "" : `, ${num(e.p2 ?? 12345)}`}${e.p3 === null ? "" : `, ${num(e.p3)}`});`);
common("randomwalk", "randomwalk", "Random walk", "⌁", 71.2, "semantic", [{ key: "p1", label: "Steps", input: "number", min: 2, max: 3000, step: 10 }, nullableNumber("p2", "Seed", 0), nullableNumber("p3", "Step scale", .1, .1)], (e) => { e.p1 = 200; }, (s, e) => { const p1 = argNumber(s.args, 2), p2 = argNumber(s.args, 3), p3 = argNumber(s.args, 4); if (p1 === null || s.args.length < 3 || s.args.length > 5 || (s.args.length > 3 && p2 === null) || (s.args.length > 4 && p3 === null)) return false; Object.assign(e, { p1, p2, p3 }); return true; }, (e) => `randomwalk(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 200)}${e.p2 === null && e.p3 === null ? "" : `, ${num(e.p2 ?? 12345)}`}${e.p3 === null ? "" : `, ${num(e.p3)}`});`);
common("lln", "lln", "Law of Large Numbers", "½→", 71.3, "semantic", [{ key: "p1", label: "Coin flips", input: "number", min: 10, max: 5000, step: 10 }, nullableNumber("p2", "Seed", 0), nullableNumber("p3", "Width", 1), nullableNumber("p4", "Height", 1)], (e) => { e.p1 = 500; }, (s, e) => { const ps = [2, 3, 4, 5].map((i) => argNumber(s.args, i)); if (ps[0] === null || s.args.length < 3 || s.args.length > 6 || (s.args.length > 3 && ps[1] === null) || (s.args.length > 4 && ps[2] === null) || (s.args.length > 5 && ps[3] === null)) return false; [e.p1, e.p2, e.p3, e.p4] = ps; return true; }, (e) => `lln(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 500)}${e.p2 === null && e.p3 === null && e.p4 === null ? "" : `, ${num(e.p2 ?? 12345)}`}${e.p3 === null && e.p4 === null ? "" : `, ${num(e.p3 ?? 680)}`}${e.p4 === null ? "" : `, ${num(e.p4)}`});`);
common("clt", "clt", "Central Limit Theorem", "x̄▥", 71.4, "semantic", [{ key: "p1", label: "Dice per average", input: "number", min: 1, max: 100, step: 1 }, { key: "p2", label: "Experiments", input: "number", min: 10, max: 5000, step: 10 }, nullableNumber("p3", "Seed", 0), nullableNumber("p4", "Width", 1), nullableNumber("p5", "Height", 1), rainbowField], (e) => { e.p1 = 10; e.p2 = 500; }, (s, e) => { const ps = [2, 3, 4, 5, 6].map((i) => argNumber(s.args, i)), paint = paintArg(s, 7); if (ps[0] === null || ps[1] === null || s.args.length < 4 || s.args.length > 8 || (s.args.length > 4 && ps[2] === null) || (s.args.length > 5 && ps[3] === null) || (s.args.length > 6 && ps[4] === null) || paint === false) return false; [e.p1, e.p2, e.p3, e.p4, e.p5] = ps; e.constructorPaint = paint; e.color = paint && paint !== "rainbow" ? paint : "cyan"; return true; }, (e) => `clt(${e.id}, ${pt(e.x, e.y)}, ${num(e.p1 ?? 10)}, ${num(e.p2 ?? 500)}${e.p3 === null && e.p4 === null && e.p5 === null && e.constructorPaint === null ? "" : `, ${num(e.p3 ?? 12345)}`}${e.p4 === null && e.p5 === null && e.constructorPaint === null ? "" : `, ${num(e.p4 ?? 560)}`}${e.p5 === null && e.constructorPaint === null ? "" : `, ${num(e.p5 ?? 260)}`}${e.constructorPaint === null ? "" : `, ${e.constructorPaint}`});`);
