// Regenerate src/catalog.ts from the manic engine's authoritative builtin
// catalog (crates/manic-lang/src/catalog.rs — test-enforced against the
// engine registry, so it cannot drift from what the engine actually supports).
//
//   npm run catalog:sync            (MANIC_REPO overrides the repo path)

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manicRepo = process.env.MANIC_REPO ?? resolve(root, "../../manic");

const json = execFileSync("cargo", ["run", "-q", "-p", "manic-lang", "--example", "dump_catalog"], {
  cwd: manicRepo,
  encoding: "utf8",
  maxBuffer: 64 * 1024 * 1024,
});
const catalog = JSON.parse(json);

const output = `// GENERATED by scripts/sync-catalog.mjs from the manic engine's builtin
// catalog (manic-lang/src/catalog.rs). Do not edit — run \`npm run catalog:sync\`.
//
// ${catalog.builtins.length} builtins · kits: ${[...new Set(catalog.builtins.map((entry) => entry.kit))].join(" ")}

export interface CatalogParam { name: string; ty: string; optional: boolean; }
export interface CatalogEntry {
  name: string;
  kind: "ctor" | "verb" | "mutverb";
  kit: string;
  summary: string;
  params: CatalogParam[];
}
export interface EngineCatalog {
  builtins: CatalogEntry[];
  colors: string[];
  easings: string[];
  templates: string[];
  canvasPresets: string[];
}

export const CATALOG: EngineCatalog = ${JSON.stringify(catalog, null, 0)};

const byName = new Map(CATALOG.builtins.map((entry) => [entry.name, entry]));
export function catalogEntry(name: string): CatalogEntry | undefined {
  return byName.get(name);
}
export const CATALOG_KITS: string[] = [...new Set(CATALOG.builtins.map((entry) => entry.kit))];
`;

writeFileSync(resolve(root, "src/catalog.ts"), output);
console.log(`src/catalog.ts: ${catalog.builtins.length} builtins from ${manicRepo}`);
