// Schema-driven entity inspector: shared fields plus the entity definition's
// declared fields — onboarding a new kind never edits this file.

import { defFor, docSize, entityAnchor, sanitizeId, translateEntity, type FieldSpec, type SceneDoc, type SceneEntity } from "../index.js";
import { ColorField } from "./ColorField.js";
import { LatexField } from "./LatexField.js";

interface InspectorProps {
  doc: SceneDoc;
  entity: SceneEntity | null;
  /** Entities temporarily faded on the canvas (view-only — never written to the file). */
  dimmed: ReadonlySet<string>;
  onSelect(id: string): void;
  onToggleDim(id: string): void;
  onChange(change: (entity: SceneEntity) => void): void;
  onRename(next: string): void;
  onDuplicate(): void;
  onRemove(): void;
  /** Host hook: open the source editor at a character offset. */
  onRevealSource?(offset: number): void;
}

export function Inspector({ doc, entity, dimmed, onSelect, onToggleDim, onChange, onRename, onDuplicate, onRemove, onRevealSource }: InspectorProps) {
  return (
    <aside className="mse-inspector">
      <div className="mse-inspector-heading">
        <span className="mse-eyebrow">INSPECTOR</span>
        <strong>{entity ? defFor(entity).label : "Nothing selected"}</strong>
      </div>

      {doc.entities.length > 0 && (
        <div className="mse-entity-list" aria-label="Entities">
          {railEntries(doc).map((entry) => (
            <span key={entry.key} className={`mse-entity-chip${entry.ids.includes(entity?.id ?? "") ? " active" : ""}${dimmed.has(entry.ids[0]) ? " dimmed" : ""}${entry.locked ? " locked" : ""}`}>
              <button className="mse-entity-name" title={entry.hint} onClick={() => onSelect(entry.ids[0])}>
                {entry.label}
              </button>
              <button
                className="mse-entity-eye"
                title={dimmed.has(entry.ids[0]) ? "Undim on canvas" : "Dim on canvas (view only — the file is untouched)"}
                aria-label={`Toggle canvas dim for ${entry.label}`}
                onClick={() => { for (const id of entry.ids) onToggleDim(id); }}
              >
                {dimmed.has(entry.ids[0]) ? "◌" : "◉"}
              </button>
            </span>
          ))}
        </div>
      )}

      {!entity && (
        <p className="mse-inspector-empty">Select an object on the canvas — or in the list above — to edit its meaning, placement, and style. Overlapping things? Dim what's in the way with ◉.</p>
      )}

      {entity?.origin === "generated" && (
        <div className="mse-locked" role="status">
          <strong>Generated by a loop or macro</strong>
          <p>One expanded instance — it has no statement of its own. Edit the loop instead, or duplicate this instance as a literal.</p>
          <LockedFacts entity={entity} />
          <div className="mse-inspector-actions">
            {onRevealSource && entity.src && (
              <button className="mse-reveal" onClick={() => onRevealSource(entity.src!.start)}>
                ✎ Edit the loop in Source
              </button>
            )}
            <button onClick={onDuplicate}>Duplicate as literal</button>
          </div>
        </div>
      )}

      {entity?.origin === "computed" && (
        <p className="mse-vars-chip" role="status">
          ƒ uses variables — position edits keep the expressions (a drag writes <code>cx − 140</code>, not a bare number).
          {onRevealSource && entity.src && (
            <button className="mse-vars-jump" onClick={() => onRevealSource(entity.src!.start)}>view source</button>
          )}
        </p>
      )}

      {entity && entity.origin !== "generated" && (
        <>
          <label className="mse-field">
            <span>Name</span>
            <input
              value={entity.id}
              disabled={entity.origin === "computed"}
              title={entity.origin === "computed" ? "Renaming a variable-driven entity could break beats inside loops — rename it in Source." : undefined}
              onChange={(event) => onRename(sanitizeId(event.target.value) || entity.id)}
              spellCheck={false}
            />
          </label>

          <PositionFields entity={entity} onChange={onChange} />

          {defFor(entity).fields.map((field) => (
            <Field key={field.key} field={field} entity={entity} template={doc.template} onChange={onChange} />
          ))}

          <div className="mse-field">
            <span>Color</span>
            <ColorField
              value={entity.color}
              template={doc.template}
              onChange={(next) => next !== null && onChange((draft) => { draft.color = next; })}
            />
            {entity.hue && <small>hue({Math.round(entity.hue.deg)}°) overrides this color</small>}
          </div>

          <label className="mse-field">
            <span>Starts</span>
            <select value={entity.reveal} onChange={(event) => onChange((draft) => { draft.reveal = event.target.value as SceneEntity["reveal"]; })}>
              <option value="none">Visible from the start</option>
              <option value="fade">Hidden — shown with a fade</option>
              <option value="grow">Hidden — grows in from center</option>
            </select>
            <small>Hidden entities need a Show beat in the story.</small>
          </label>

          <div className="mse-field-grid">
            <label className="mse-field">
              <span>Opacity</span>
              <input type="range" min={0.1} max={1} step={0.05} value={entity.opacity} onChange={(event) => onChange((draft) => { draft.opacity = Number(event.target.value); })} />
            </label>
            <label className="mse-field">
              <span>Rotation</span>
              <input type="number" value={entity.rotation} step={5} onChange={(event) => onChange((draft) => { draft.rotation = Number(event.target.value) || 0; })} />
            </label>
          </div>

          <div className="mse-inspector-actions">
            <button onClick={onDuplicate}>Duplicate</button>
            <button className="mse-danger" onClick={onRemove}>Remove</button>
          </div>
        </>
      )}
    </aside>
  );
}

function PositionFields({ entity, onChange }: {
  entity: SceneEntity;
  onChange(change: (entity: SceneEntity) => void): void;
}) {
  const anchor = entityAnchor(entity);
  const move = (x: number, y: number) => onChange((draft) => {
    const at = entityAnchor(draft);
    translateEntity(draft, x - at.x, y - at.y);
  });
  return (
    <div className="mse-field-grid">
      <label className="mse-field">
        <span>X</span>
        <input type="number" value={Math.round(anchor.x)} onChange={(event) => move(Number(event.target.value) || 0, anchor.y)} />
      </label>
      <label className="mse-field">
        <span>Y</span>
        <input type="number" value={Math.round(anchor.y)} onChange={(event) => move(anchor.x, Number(event.target.value) || 0)} />
      </label>
    </div>
  );
}

/** Read-only evaluated values for a locked entity. */
function LockedFacts({ entity }: { entity: SceneEntity }) {
  const anchor = entityAnchor(entity);
  const box = defFor(entity).bounds(entity);
  const facts: [string, string][] = [
    ["kind", entity.kind],
    ["at", `${Math.round(anchor.x)}, ${Math.round(anchor.y)}`],
    ["size", `${Math.round(box.width)} × ${Math.round(box.height)}`],
    ["color", entity.hue ? `hue(${Math.round(entity.hue.deg)}°)` : entity.color],
  ];
  if (entity.tags?.length) facts.push(["tags", entity.tags.join(" ")]);
  return (
    <dl className="mse-facts">
      {facts.map(([key, value]) => (
        <div key={key}><dt>{key}</dt><dd>{value}</dd></div>
      ))}
    </dl>
  );
}

interface RailEntry { key: string; label: string; hint: string; ids: string[]; locked: boolean; }

/** Rail entries: literal/computed entities individually; generated ones grouped by their loop id pattern. */
function railEntries(doc: SceneDoc): RailEntry[] {
  const entries: RailEntry[] = [];
  const groups = new Map<string, RailEntry>();
  for (const entity of doc.entities) {
    if (entity.origin === "generated") {
      const key = `gen:${entity.genKey ?? entity.id}`;
      const existing = groups.get(key);
      if (existing) {
        existing.ids.push(entity.id);
        existing.label = `${entity.genKey ?? entity.id} ×${existing.ids.length}`;
        continue;
      }
      const entry: RailEntry = { key, label: entity.genKey ?? entity.id, hint: "Generated by a loop — locked", ids: [entity.id], locked: true };
      groups.set(key, entry);
      entries.push(entry);
      continue;
    }
    entries.push({
      key: entity.id,
      label: entity.id,
      hint: entity.origin === "computed" ? `${entity.id} (${entity.kind}) — variable-positioned, locked` : `Select ${entity.id} (${entity.kind})`,
      ids: [entity.id],
      locked: entity.origin === "computed",
    });
  }
  return entries;
}

function Field({ field, entity, template, onChange }: {
  field: FieldSpec;
  entity: SceneEntity;
  template: SceneDoc["template"];
  onChange(change: (entity: SceneEntity) => void): void;
}) {
  const record = entity as unknown as Record<string, unknown>;
  const value = record[field.key];

  function set(next: unknown) {
    onChange((draft) => { (draft as unknown as Record<string, unknown>)[field.key] = next; });
  }

  switch (field.input) {
    case "textarea":
      return (
        <label className="mse-field">
          <span>{field.label}</span>
          <textarea value={String(value ?? "")} onChange={(event) => set(event.target.value)} />
          {field.hint && <small>{field.hint}</small>}
        </label>
      );
    case "text":
      return (
        <label className="mse-field">
          <span>{field.label}</span>
          <input value={String(value ?? "")} onChange={(event) => set(event.target.value)} />
        </label>
      );
    case "range":
      return (
        <label className="mse-field">
          <span>{field.label}</span>
          <input
            type="range" min={field.min} max={field.max} step={field.step}
            value={Number(value ?? field.min ?? 0)}
            onChange={(event) => set(Number(event.target.value))}
          />
          <small>{String(value ?? "")}{typeof value === "number" ? "px" : ""}</small>
        </label>
      );
    case "number":
      return (
        <label className="mse-field">
          <span>{field.label}</span>
          <input
            type="number" min={field.min} max={field.max} step={field.step}
            value={value === null || value === undefined ? "" : Number(value)}
            placeholder={field.nullable ? "engine default" : undefined}
            onChange={(event) => {
              const raw = event.target.value;
              if (raw === "" && field.nullable) return set(null);
              set(Number(raw) || 0);
            }}
          />
          {field.hint && <small>{field.hint}</small>}
        </label>
      );
    case "select":
      return (
        <label className="mse-field">
          <span>{field.label}</span>
          <select value={String(value ?? "")} onChange={(event) => set(event.target.value)}>
            {(field.options ?? []).map((option) => <option key={option} value={option}>{option}</option>)}
          </select>
        </label>
      );
    case "latex":
      return (
        <div className="mse-field">
          <span>{field.label}</span>
          <LatexField value={String(value ?? "")} onChange={(next) => set(next)} />
        </div>
      );
    case "color":
      return (
        <div className="mse-field">
          <span>{field.label}</span>
          <ColorField
            value={value === null || value === undefined ? null : String(value)}
            template={template}
            nullable={field.nullable}
            onChange={(next) => set(next)}
          />
        </div>
      );
    case "checkbox":
      return (
        <label className="mse-field mse-field-checkbox">
          <input type="checkbox" checked={Boolean(value)} onChange={(event) => set(event.target.checked)} />
          <span>{field.label}</span>
        </label>
      );
  }
}
