// The story: named steps of verb beats with together / sequence / stagger
// timing. Pure authoring — there is deliberately NO in-canvas playback:
// results may vary from the engine, so watching the story always means the
// real thing (▶ Preview with Manic). Verb inputs render from each verb
// definition's declared UI — onboarding a new verb never edits this file.

import { useState } from "react";
import {
  EASINGS, allVerbDefs, verbDef,
  type SceneAction, type SceneDoc, type SceneEntity, type StepMode,
} from "../index.js";
import { ColorField } from "./ColorField.js";
import { LatexField } from "./LatexField.js";

interface StoryProps {
  doc: SceneDoc;
  selectedAction: { step: number; index: number } | null;
  selectedEntity: SceneEntity | null;
  warnings: string[];
  onSelectAction(next: { step: number; index: number } | null): void;
  onAddAction(stepIndex: number, verb: string): void;
  onMutate(change: (draft: SceneDoc) => void): void;
  onPreview?(): void;
}

export function Story({ doc, selectedAction, selectedEntity, warnings, onSelectAction, onAddAction, onMutate, onPreview }: StoryProps) {
  const [verbMenuFor, setVerbMenuFor] = useState<number | null>(null);
  const activeAction = selectedAction ? doc.steps[selectedAction.step]?.actions[selectedAction.index] ?? null : null;

  function mutateAction(change: (action: SceneAction) => void) {
    if (!selectedAction) return;
    onMutate((draft) => {
      const action = draft.steps[selectedAction.step]?.actions[selectedAction.index];
      if (action) change(action);
    });
  }

  return (
    <div className="mse-story">
      <div className="mse-story-head">
        <span className="mse-eyebrow">STORY</span>
        <span className="mse-story-hint">Steps play in order. To watch it, run the real engine — the canvas never approximates playback.</span>
        {onPreview && <button className="mse-primary" onClick={onPreview}>▶ Preview with Manic</button>}
      </div>

      <div className="mse-steps">
        {doc.steps.map((step, stepIndex) => step.origin ? (
          <div className="mse-step mse-step-locked" key={stepIndex} title={step.origin === "generated" ? "Generated by a loop/macro — edit in Source" : "Uses variables — edit in Source"}>
            <div className="mse-step-head"><span className="mse-step-locked-name">{step.name} 🔒</span></div>
            <div className="mse-step-actions">
              {step.actions.slice(0, 6).map((action, actionIndex) => (
                <span key={actionIndex} className="mse-action-chip">
                  <strong>{verbDef(action.verb)?.label.toLowerCase() ?? action.verb}</strong>
                  {action.target && <span>{action.target}</span>}
                </span>
              ))}
              {step.actions.length > 6 && <span className="mse-action-chip"><small>+{step.actions.length - 6} more</small></span>}
            </div>
          </div>
        ) : (
          <div className="mse-step" key={stepIndex}>
            <div className="mse-step-head">
              <input
                value={step.name}
                onChange={(event) => onMutate((draft) => { draft.steps[stepIndex].name = event.target.value; })}
                aria-label="Step name"
                spellCheck={false}
              />
              <div className="mse-step-tools">
                <button disabled={stepIndex === 0} title="Move step earlier" onClick={() => onMutate((draft) => { const steps = draft.steps; [steps[stepIndex - 1], steps[stepIndex]] = [steps[stepIndex], steps[stepIndex - 1]]; })}>◀</button>
                <button disabled={stepIndex >= doc.steps.length - 1} title="Move step later" onClick={() => onMutate((draft) => { const steps = draft.steps; [steps[stepIndex + 1], steps[stepIndex]] = [steps[stepIndex], steps[stepIndex + 1]]; })}>▶</button>
                <button title="Remove step" onClick={() => { onSelectAction(null); onMutate((draft) => { draft.steps.splice(stepIndex, 1); }); }}>×</button>
              </div>
            </div>
            <div className="mse-step-mode">
              <select value={step.mode} onChange={(event) => onMutate((draft) => { draft.steps[stepIndex].mode = event.target.value as StepMode; })} aria-label="Step timing">
                <option value="together">together</option>
                <option value="sequence">one after another</option>
                <option value="stagger">staggered</option>
              </select>
              {step.mode === "stagger" && (
                <input
                  type="number" min={0.05} step={0.05} value={step.gap}
                  onChange={(event) => onMutate((draft) => { draft.steps[stepIndex].gap = Math.max(0.05, Number(event.target.value) || 0.15); })}
                  aria-label="Stagger gap seconds"
                />
              )}
            </div>
            <div className="mse-step-actions">
              {step.actions.map((action, actionIndex) => {
                const active = selectedAction?.step === stepIndex && selectedAction.index === actionIndex;
                return (
                  <button
                    key={actionIndex}
                    className={`mse-action-chip${active ? " active" : ""}`}
                    onClick={() => onSelectAction(active ? null : { step: stepIndex, index: actionIndex })}
                  >
                    <strong>{verbDef(action.verb)?.label.toLowerCase() ?? action.verb}</strong>
                    {action.target && <span>{action.target}</span>}
                    <small>{action.dur}s</small>
                  </button>
                );
              })}
              <div className="mse-add-action">
                <button onClick={() => setVerbMenuFor((current) => (current === stepIndex ? null : stepIndex))}>+ Beat</button>
                {verbMenuFor === stepIndex && (
                  <div className="mse-verb-menu">
                    {allVerbDefs().map((verb) => {
                      const enabled = verb.targetless || (selectedEntity ? verb.appliesTo(selectedEntity.kind) : false);
                      return (
                        <button key={verb.name} disabled={!enabled} title={verb.hint} onClick={() => { setVerbMenuFor(null); onAddAction(stepIndex, verb.name); }}>
                          <strong>{verb.label}</strong>
                          <small>{verb.hint}</small>
                        </button>
                      );
                    })}
                    {!selectedEntity && <p>Select an entity on the canvas to add beats for it. Wait is always available.</p>}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
        <button
          className="mse-add-step"
          onClick={() => onMutate((draft) => draft.steps.push({ name: `Step ${draft.steps.length + 1}`, mode: "together", gap: 0.15, actions: [] }))}
        >
          + Step
        </button>
      </div>

      {activeAction && selectedAction && (() => {
        const spec = verbDef(activeAction.verb);
        if (!spec) return null;
        return (
          <div className="mse-action-editor">
            <strong>{spec.label}</strong>
            {!spec.targetless && (
              <label>
                <span>Target</span>
                <select
                  value={activeAction.target}
                  onChange={(event) => mutateAction((action) => { action.target = event.target.value; })}
                >
                  {doc.entities.filter((entity) => spec.appliesTo(entity.kind)).map((entity) => (
                    <option key={entity.id} value={entity.id}>{entity.id}</option>
                  ))}
                </select>
              </label>
            )}
            {spec.ui.propOptions && (
              <label>
                <span>Property</span>
                <select value={activeAction.prop ?? spec.ui.propOptions[0]} onChange={(event) => mutateAction((action) => { action.prop = event.target.value; })}>
                  {spec.ui.propOptions.map((prop) => <option key={prop} value={prop}>{prop}</option>)}
                </select>
              </label>
            )}
            {spec.ui.point && (
              <>
                <label>
                  <span>{spec.ui.point === "delta" ? "Δx" : "x"}</span>
                  <input type="number" value={activeAction.point?.x ?? 0} onChange={(event) => mutateAction((action) => { action.point = { x: Number(event.target.value) || 0, y: action.point?.y ?? 0 }; })} />
                </label>
                <label>
                  <span>{spec.ui.point === "delta" ? "Δy" : "y"}</span>
                  <input type="number" value={activeAction.point?.y ?? 0} onChange={(event) => mutateAction((action) => { action.point = { x: action.point?.x ?? 0, y: Number(event.target.value) || 0 }; })} />
                </label>
              </>
            )}
            {spec.ui.amount && (
              <label>
                <span>{spec.ui.amount.label}</span>
                <input type="number" step={spec.ui.amount.step} value={activeAction.amount ?? 0} onChange={(event) => mutateAction((action) => { action.amount = Number(event.target.value) || 0; })} />
              </label>
            )}
            {spec.ui.wordsArg && (
              <div className="mse-action-latex">
                <span>{spec.ui.wordsArg.label}</span>
                <textarea
                  className="mse-action-words"
                  value={activeAction.text ?? ""}
                  onChange={(event) => mutateAction((action) => { action.text = event.target.value; })}
                  rows={2}
                  spellCheck={false}
                />
              </div>
            )}
            {spec.ui.latexArg && (
              <div className="mse-action-latex">
                <span>{spec.ui.latexArg.label}</span>
                <LatexField value={activeAction.text ?? ""} onChange={(next) => mutateAction((action) => { action.text = next; })} />
              </div>
            )}
            {spec.ui.colorArg && (
              <div className="mse-action-color">
                <span>Color</span>
                <ColorField
                  value={activeAction.color}
                  template={doc.template}
                  nullable
                  onChange={(next) => mutateAction((action) => { action.color = next; })}
                />
              </div>
            )}
            <label>
              <span>{spec.ui.durLabel}</span>
              <input type="number" min={0.05} step={0.05} value={activeAction.dur} onChange={(event) => mutateAction((action) => { action.dur = Math.max(0.05, Number(event.target.value) || 0.05); })} />
            </label>
            {spec.hasEase && (
              <label>
                <span>Easing</span>
                <select value={activeAction.ease} onChange={(event) => mutateAction((action) => { action.ease = event.target.value as typeof action.ease; })}>
                  {EASINGS.map((ease) => <option key={ease} value={ease}>{ease}</option>)}
                </select>
              </label>
            )}
            <div className="mse-action-editor-buttons">
              <button
                disabled={selectedAction.index === 0}
                onClick={() => {
                  onMutate((draft) => {
                    const actions = draft.steps[selectedAction.step].actions;
                    [actions[selectedAction.index - 1], actions[selectedAction.index]] = [actions[selectedAction.index], actions[selectedAction.index - 1]];
                  });
                  onSelectAction({ step: selectedAction.step, index: selectedAction.index - 1 });
                }}
              >◀</button>
              <button
                disabled={selectedAction.index >= (doc.steps[selectedAction.step]?.actions.length ?? 0) - 1}
                onClick={() => {
                  onMutate((draft) => {
                    const actions = draft.steps[selectedAction.step].actions;
                    [actions[selectedAction.index + 1], actions[selectedAction.index]] = [actions[selectedAction.index], actions[selectedAction.index + 1]];
                  });
                  onSelectAction({ step: selectedAction.step, index: selectedAction.index + 1 });
                }}
              >▶</button>
              <button
                className="mse-danger"
                onClick={() => {
                  onMutate((draft) => draft.steps[selectedAction.step].actions.splice(selectedAction.index, 1));
                  onSelectAction(null);
                }}
              >Remove beat</button>
            </div>
          </div>
        );
      })()}

      {warnings.length > 0 && (
        <div className="mse-story-warnings" role="status">
          {warnings.map((warning, index) => <span key={index}>⚠ {warning}</span>)}
        </div>
      )}
    </div>
  );
}
